### ISSUE TITLE
Add support of local plugins

### ISSUE THREAD

**Issue by roadhump** [mantoni/eslint_d.js#10]
`eslint_d` does not resolve local plugins in project's `node_modules` as `eslint` does

It means 
```
npm install eslint eslint_d babel-eslint --save-dev

// .eslintrc
{"parser": "babel-eslint"}

$ ./node_modules/.bin/eslint_d src/1.js 

/Users/roadhump/Projects/xx/src/1.js
  0:0  error  Cannot find module 'babel-eslint'

$ ./node_modules/.bin/eslint_d src/1.js 
// no errors
```

**Comment by mantoni** [comment]
I guess I know why this happens: eslint uses a simple `require` statement to load the configured parser. If the eslint_d server was started in a directory that doesn't have the parser in the node_modules resolve path, it can't find the parser. You can easily check by running `eslint_d restart`, which should fix it.

A possible solution could be to run a new eslint_d server for each directory in use, or restart the existing one transparently whenever the directory changes. Any other ideas?

**Comment by Schniz** [comment]
Maybe: whenever I call to eslint_d, it adds the current directory to the module resolver, and removes it afterwards?

**Comment by Schniz** [comment]
Or synlinking and unlinking afterwards

**Comment by mantoni** [comment]
Just release `eslint_d v2.2.0` which addressws this issue. See [the changelog entry](https://github.com/mantoni/eslint_d.js/blob/master/CHANGES.md#220) for details.

@roadhump @Schniz Can you please test whether this works for you now? I'd appreciate your feedback, or new issues in case things don't work as expected.

**Comment by roadhump** [comment]
@mantoni seems working just fine, thank you!

**Comment by Schniz** [comment]
@mantoni works great! :+1:

**Comment by expelledboy** [comment]
@mantoni Amazing work! I have just noticed that if I change the plugin configuration in `.eslintrc` after using eslint_d that it requires a `eslint_d restart`. Would be useful if it was auto-restarted on changes to that file, or just add a note to the README.

**Comment by mantoni** [comment]
Yes, this could be added to the readme…
