### ISSUE TITLE
Error: Cannot find module 'chalk' from '$PROJECT_DIR/node_modules/eslint/lib'

### ISSUE THREAD

**Issue by cdfa** [mantoni/eslint_d.js#101]
Hi, I'm getting this error running `npx eslint_d some-file.js`. I'm using npx, because otherwise it can' find any package binaries. I installed both eslint and eslintd locally in my project.

**Comment by mantoni** [comment]
I can't reproduce with `npx eslint_d some-file.js`. I will need some more details about your setup. Can you try to reproduce in a minimal repository?

What do you mean by "… because otherwise it can' find any package binaries"?

**Comment by cdfa** [comment]
It seems the problem was having it installed with [pnpm](https://pnpm.js.org/). Weird that that matters though.
If I run it without npx it says `Unknown command 'eslint_d'`, but I think that's with all packages I installed.

**Comment by mantoni** [comment]
I guess you installed it in `node_modules`. For `eslint_d` to be available, you have to install it globally with `npm i -g eslint_d`.

**Comment by cdfa** [comment]
I tried that first as well, but it my editor didn't pick it up properly, which isn't your problem, but why can it not be installed locally?

**Comment by cdfa** [comment]
> Local install is fine. You'd have to run it with node_modules/.bin/eslint_d file.js though.

This is more or less what npx does.
After more testing and actually trying to run eslint_d when installed globally with pnpm I get this error:
```Error: ENOENT: no such file or directory, open '/home/cdfa/Projects/ll-node-package-example/node_modules/.registry.npmjs.org/eslint/5.9.0/node_modules/eslint/lib/api.js'```

It's clear that is this could be solved by just using npm instead, but pnpm is 100% compatible with the NodeJS module resolution standard, so either this package or one of it's dependencies does not implement this correctly, or there's a bug in pnpm. Do you know of anything that could put me on the right track?

**Comment by mantoni** [comment]
I don't use pnpm myself, but if you find out how to fix it, I'd be happy to merge a patch.

**Comment by mantoni** [comment]
Fixed in `v9.1.1`.
