### ISSUE TITLE
The difference between eslint and eslint_d?

### ISSUE THREAD

**Issue by fetatefog** [mantoni/eslint_d.js#102]
I saw people mention this package in reddit and I just come across. I am not sure what the difference between the two. Especially, in the page, they state that  
> If you want to lint from within your editor whenever you save a file, eslint_d is for you.

So does it works in real time like eslint? I am emacs user and I could configure flycheck to check my js file while typing so will eslint_d able to do this too? Please help me clarify this. I just want to learn about it. Thanks.

**Comment by aaronjensen** [comment]
Hi @fetatefog, I don't mean to be rude, but have you read the [readme](https://github.com/mantoni/eslint_d.js/blob/master/README.md)? 

It does a pretty good job explaining what eslint_d is, but if you have specific questions after reading it, feel free to ask them or let us know if something is unclear.

For Emacs/flycheck, see [this section of the README](https://github.com/mantoni/eslint_d.js/blob/master/README.md#linting). Also, if you want automatic fixing on save, you can use the [eslintd-fix package](https://github.com/aaronjensen/eslintd-fix) as described in [this section of the README](https://github.com/mantoni/eslint_d.js/blob/master/README.md#automatic-fixing)

**Comment by mantoni** [comment]
The goal of eslint_d is to behave as close as possible to eslint itself and just improve performance to be more suitable as an editor plugin.

As @aaronjensen pointed out, you can use eslint_d with emacs. Please follow the instructions in the readme. If you’re having trouble with it, feel free to open a new issue with a more specific question.
