### ISSUE TITLE
Add information about --cache in the readme 

### ISSUE THREAD

**Issue by netei** [mantoni/eslint_d.js#11]
As your software was created to improve eslint speed, you could maybe specify that to get an even better speed improvement, you can use --cache (which is an eslint option).

What do you think ?

**Comment by mantoni** [comment]
Sure, makes sense. However, the main goal was to speed it up for editor integration. In that use case individual files get linted and the cache doesn't improve anything.

If you still feel like the caching options should be highlighted here, I'd merge your suggestion :)
