### ISSUE TITLE
Missing commands information in --help 

### ISSUE THREAD

**Issue by roadhump** [mantoni/eslint_d.js#14]
It seems like in version 2.2.0  `eslint_d --help` outputs `eslint` help without mentioning `eslint_d` commands.

**Comment by mantoni** [comment]
Haha, true. I'm just forwarding everything unless there is some explicit handling for an option. `--help` completely fell under the radar.

**Comment by mantoni** [comment]
Oh, I just realized, in case of `--help`, I even just copied the eslint options for opinionator minus the ones that I don't support (yet).

**Comment by mantoni** [comment]
This has been addressed with the new major `v14.0.0` (see #294). Thank you.
