### ISSUE TITLE
High memory usage

### ISSUE THREAD

**Issue by Luke-zhang-04** [mantoni/eslint_d.js#140]
eslint_d is really fast, but it takes up 500mbs of RAM (and sometimes more), which can really add up. I'm not sure if this is a memory leak, or if the RAM is needed to make it this fast.

![image](https://user-images.githubusercontent.com/55749227/94342425-00892800-ffdf-11ea-8245-239df2f769c6.png)

**Comment by mantoni** [comment]
It caches the eslint instance along with all loaded plugins for the last 10 projects. You can see how many projects are cached with `eslint_d status`. Try `eslint_d restart` and then lint a file in one of the projects to see whether the initial memory footprint seems reasonable. It shouldn't go up much from there over time unless you're loading more projects.

**Comment by Luke-zhang-04** [comment]
Ok thanks
