### ISSUE TITLE
Incorrect indentation on fix.

### ISSUE THREAD

**Issue by cloggier** [mantoni/eslint_d.js#142]
When fixing (or fixing to stdout) `eslint_d` does not indent fixed lines properly.

Input code:

```
<template>
  <section class="navbar-container">
    <v-app-bar color="#fff"
      flat
    />
  </section>
</template>
```

(according to my eslint rules `color` directive on line 3 must be on separate line (`'color' should be on a new line. [Warning/vue/max-attributes-per-line]`)

and `eslint <file> --fix` corrects it to:

```
<template>
  <section class="navbar-container">
    <v-app-bar
      color="#fff"
      flat
    />
  </section>
</template>
```

while `cat <file> | eslint_d --stdin --fix-to-stdout` will produce:

```
<template>
  <section class="navbar-container">
    <v-app-bar
color="#fff"
      flat
    />
  </section>
</template>
```

Am I doing something wrong or is that a bug?

**Comment by mantoni** [comment]
Interesting. Can you run `eslint_d restart` and try to reproduce again? Just to make sure you don't have a different version of `eslint` or a different config cached in the daemon.

**Comment by cloggier** [comment]
Was hoping that was such an easy fix, unfortunately still not indenting correctly.

Perhaps my installation is a problem (I am not an expert when it comes to JS)? I have `eslint_d` installed globally but `eslint` is in project's scope.

```
$ ./node_modules/eslint/bin/eslint.js --version
v6.8.0
$ eslint_d --version
v7.17.0 (eslint_d v9.1.2)
```

**Comment by mantoni** [comment]
You did everything the way it's supposed to be set up. I also have `eslint_d` installed globally and it will pick up the local install per project.

If you have time to look into it some more, that'd be great.

**Comment by cloggier** [comment]
I do have time now, not sure how much more debugging I can do by myself. Is there anything else you would like me to try?

**Comment by mantoni** [comment]
The most helpful thing would be a pull request with a unit test that reproduces the issue 🙂

**Comment by mantoni** [comment]
I'm failing to reproduce this with a test. The code section that deals with `--fix` and `--fix-to-stdout` is rather simple:

https://github.com/mantoni/eslint_d.js/blob/2b42e64643bb9efe99b3cf5e803a0285785d254e/lib/linter.js#L125-L132

There is no further processing of the output from eslint. Not sure there is anything I can do about it 🤔

**Comment by cloggier** [comment]
Interesting. It happens every time for me. (Notice `absolute` prop location.)

```
$ head -n4 src/App.vue
<template>
  <v-app>
    <v-progress-linear absolute
      :active="loading"
$ cat src/App.vue|eslint_d --fix-to-stdout --stdin|head -n 5
<template>
  <v-app>
    <v-progress-linear
absolute
      :active="loading"
$ ./node_modules/eslint/bin/eslint.js --fix src/App.vue
$ head -n5 src/App.vue
<template>
  <v-app>
    <v-progress-linear
      absolute
      :active="loading"
$
```

So `eslint` fixed badly indented line. It also properly indents in the first place:

```
$ head -n4 src/App.vue
<template>
  <v-app>
    <v-progress-linear absolute
      :active="loading"
$ ./node_modules/eslint/bin/eslint.js --fix src/App.vue
$ head -n5 src/App.vue
<template>
  <v-app>
    <v-progress-linear
      absolute
      :active="loading"
$
```

Versions are:

```
$ ./node_modules/eslint/bin/eslint.js --version
v6.8.0
$ eslint_d --version
v7.17.0 (eslint_d v9.1.2)
$
```

(what is v7.17.0 version relating to? eslint?)

What else should I try?

Thanks for looking into it!

**Comment by mantoni** [comment]
> what is v7.17.0 version relating to? eslint?

That is the version of eslint that ships with eslint_d. It's only used when there is no local install.

You could try to create a minimal project reproducing the issue, ideally with as few custom eslint rules as possible. That would help a lot. Thanks.

**Comment by mantoni** [comment]
I think I found the culprit. With eslint 7, a new `ESLint` class API has been introduced and the `CLIEngine` class has been deprecated, but not removed. I think you found a small difference in the behaviours of those two implementations.

Announcement on the eslint blog: https://eslint.org/blog/2020/02/whats-coming-in-eslint-7.0.0#eslint-class-replacing-cliengine-class

This project will have to move to the `ESLint` class implementation for v7 and up since `CLIEngine` will be removed in a future major release of `eslint`. For projects using eslint v6 and below, `eslint_d` should continue to use `CLIEngine` so that we can continue to support projects depending on older `eslint` versions.

@cloggier Thanks a lot for your patience. If you feel like looking into this, I'd gratefully help and review.

**Comment by cloggier** [comment]
Ah, nicely done! Thank you so much for looking into this. I don't think I can help any Forster though, although I would love to, I am only learning JS and Vue right now, definitely have no knowledge nor experience to put fixing PR in place…

**Comment by mantoni** [comment]
`v10.0.0` is out which uses the new `ESLint` API. Please check if this fixes your issue 🙏.

**Comment by cloggier** [comment]
I just have, with great excitement, but unfortunately it still ignores indent.

**Comment by cloggier** [comment]
@mantoni out of interest, can you still reproduce it?

**Comment by mantoni** [comment]
I suppose #145 is related.

**Comment by cloggier** [comment]
I am not sure what relevance `--stdin-filename` has but adding it to my command seems to be fixing indentation issue.
@mantoni Is that intended way of calling eslint_d [Further-Integration-Examples#eslint_d](https://github.com/neovim/nvim-lspconfig/wiki/Further-Integration-Examples#eslint_d)?

**Comment by mantoni** [comment]
That's very interesting. I always thought the filename setting is only used when generating the error report. If it fixes your issue, there seems to be more to it. Maybe the vue plugin is activated by the filename suffix?

**Comment by cloggier** [comment]
Not sure why it makes is work, but since it does I think this issue can be closed now. If you feel like it should work just fine without that extra argument feel free to reopen. Great thanks for making eslint usable(!) and all your help in that issue. Outstanding!

**Comment by mantoni** [comment]
Thank you for sticking with it and your help testing attempts to fix it.

I guess your plugin depends on the file name suffix. This should probably be stated in the readme.
