### ISSUE TITLE
eslint_d cannot find config

### ISSUE THREAD

**Issue by Aaronzinhoo** [mantoni/eslint_d.js#152]
Hi, I am trying to use `eslint_d` right now with emacs, but  within the terminal `eslint_d` cannot locate the config.

I have tried using 

```
eslint_d --print-config "<filepath>"
```

All this does though is result in an error  `Error: 'filePath' must be a non-empty string` which its not... unless I am missing something here lol. Any help is greatly appreciated since I would love to use this `flycheck` especially since it basically replaces prettier for me as well. 

Configuration:

- OS: WSL `Ubuntu-20.04`. 
- eslint_d version: `v10.0.2`
- `eslint` version: `v7.20.0`

**Comment by JForsaken** [comment]
Having the same issue on my side

**Comment by orzechowskid** [comment]
I did some digging and I think the problem is here: https://github.com/mantoni/eslint_d.js/blob/fd02100be4fd25f85ee6be1b7e9fb91cf179e7f9/lib/linter.js#L192

```diff
-    const fileConfig = await engine.calculateConfigForFile(opts.printConfig);
+    const fileConfig = await engine.calculateConfigForFile(files[0]);
```

`opts.printConfig` is a boolean but eslint wants a string.  `executeWithCLIEngine` is doing the right thing but `executeWithESLint` is not.

**Comment by mantoni** [comment]
A pull request to fix this would be very welcome 🙂👍

**Comment by Aaronzinhoo** [comment]
@orzechowskid @mantoni 
Hmm, I tried to use that change, but nothing changed when I did. I used a debugger and I do not think this line is actually hit. I am bad at debugging js code but I put a breakpoint at that line and never reached it. =(

**Comment by orzechowskid** [comment]
try running `eslint_d stop` after patching a source file, in order to terminate any running instances. then run `eslint_d --print-config <srcfile>` again.  I was able to get eslint_d to successfully detect my eslint config file at that point.

if that works for you too then I'll put up a PR as requested.

**Comment by Aaronzinhoo** [comment]
- @orzechowskid it worked like a charm. Thanks a lot for your help. Do you mind I ask you how you debugged this? I am not good debugging and would love to get better with JavaScript code now that I am working with it more.

**Comment by orzechowskid** [comment]
a few things I guess:
- noticing that there were existing unit tests for `--print-config` and seeing what they did;
- grep'ing through the eslint_d source for `--print-config` which led me to the `printConfig` variable; and
- seeing that all child process output was done via the `callback` function, so I used that as a cheap version of `console.log`.
- reading the [eslint API docs](https://eslint.org/docs/developer-guide/nodejs-api) to see what arguments `calculateConfigForFile` was expecting

(I'm sure there are better and faster ways to debug issues than what I did)

**Comment by Aaronzinhoo** [comment]
@orzechowskid that helps a lot. I tried going through the code using a gdb style node debugger and it just seemed like it never reached the linter.js file. So I figured I definitely did not have the right idea... 

Thanks for your input. Honestly I think you did it pretty well considering the debugger route went stale pretty fast.
