### ISSUE TITLE
Separate exit codes for linting errors vs. fatal config problems

### ISSUE THREAD

**Issue by jose-elias-alvarez** [mantoni/eslint_d.js#155]
Since 2018, ESLint has used [separate status codes](https://github.com/eslint/eslint/commit/1014ea2a3a33666a7f9865bd18171fb762221d0a) for linting errors (`1`) versus fatal config errors (`2`). This is pretty useful when, say, spawning a child process and reading the exit code to determine if the process itself had an error. 

It seems that eslint_d uses `1` in both situations ([linting](https://github.com/mantoni/eslint_d.js/blob/8eb60254e906f6ee8fda2365cfa9476eb8d35199/lib/linter.js#L86) and [config parsing errors](https://github.com/mantoni/eslint_d.js/blob/5db201f910a0ff88260cc9cdf632e451b769214b/lib/server.js#L48)). It's a minor feature, but is there any chance of getting eslint_d to match ESLint's behavior? I'm happy to put in a PR if it's something you'd be interested in.

**Comment by mantoni** [comment]
Absolutely! Please send a PR and I'll happily merge and cut a new release.

Thank you 🙏

**Comment by jose-elias-alvarez** [comment]
Thank you for the quick reply! I'll have time to work on this very soon.

**Comment by jose-elias-alvarez** [comment]
I've got this working locally and just want to verify that my approach makes sense before I finalize the PR, since (I think!) implementing this will require changes in both eslint_d and core_d.

As far as I can tell, core_d [will always set the exit code to 1](https://github.com/mantoni/core_d.js/blob/bfe1f7c5d5211f006e13217e8f436f507a5da450/lib/client.js#L69) if the service sends back an error. My approach is to add an optional argument to the core_d server's [handler](https://github.com/mantoni/core_d.js/blob/bfe1f7c5d5211f006e13217e8f436f507a5da450/lib/server.js#L63) to allow the service to send an error and an exit code in the format `callback(e, null, 2)`, then pass the code to [fail](https://github.com/mantoni/core_d.js/blob/bfe1f7c5d5211f006e13217e8f436f507a5da450/lib/server.js#L9) (defaulting to 1). `fail` can then end the connection with the exit code template string-ed into the buffer, and [the relevant handler](https://github.com/mantoni/core_d.js/blob/bfe1f7c5d5211f006e13217e8f436f507a5da450/lib/client.js#L68) can use a regex to check if the buffer content matches the specified format and set the exit code accordingly. 

I think (if there's not some giant flaw I'm overlooking) that this should allow services to send arbitrary exit codes on error to core_d without breaking any existing implementations, since it'll fall back to the current behavior when no exit code is specified. 

The biggest disadvantage that I can see is the potential performance penalty from using a regex test versus a string equality check, so if that's a concern, I can simply hardcode another check for `buf === "# exit 2"` to handle this specific case and call it a day.

Let me know if that approach sounds viable, and thanks for the attention on this issue.

**Comment by mantoni** [comment]
Without looking into any details, could we instead specify an `exit_code` property on the error?

I'm planning to use async / await consistently in core_d and eslint_d and it'd be nice to have a solution that doesn't make that transition harder.

**Comment by jose-elias-alvarez** [comment]
Understood. I’ll put together the PR with the code on the error itself.

**Comment by mantoni** [comment]
PRs merged and released in `v10.1.0`. Thank you!
