### ISSUE TITLE
--quiet disables --fix

### ISSUE THREAD

**Issue by dpinol** [mantoni/eslint_d.js#157]
Invoking directly eslint with `--fix --quiet` fixes the detected autofixable non-warning errors (as per eslint documentation https://eslint.org/docs/user-guide/command-line-interface#-quiet)

However, `eslint_d --fix --quiet` does not fix any error and reports to use --fix, even when it's already included:

```
/eslint_d  --quiet --fix src/cms/callback.ts

src/cms/callback.ts
  3:10  error  Delete `···`  prettier/prettier

✖ 1 problem (1 error, 0 warnings)
  1 error and 0 warnings potentially fixable with the `--fix` option.

```

**Comment by mantoni** [comment]
Interesting. Would you care to look into this and prepare a pull request?

**Comment by dpinol** [comment]
@mantoni done #165 thanks
