### ISSUE TITLE
Respect XDG

### ISSUE THREAD

**Issue by samhh** [mantoni/eslint_d.js#158]
This may belong in core_d, but the issue presents itself with eslint_d.

Upon first invocation the file `~/.eslint_d` is created. This pollutes the user's home directory. Instead, it should be placed in one of the [XDG directories](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html), potentially `$XDG_RUNTIME_DIR`.

**Comment by mantoni** [comment]
Thank you for reporting. A similar request was files in `core_d` and I agree that it belongs there.

**Comment by mantoni** [comment]
Closing since the corresponding PR in `core_d` has been merged.
