### ISSUE TITLE
Configuring eslint to use @babel/eslint-parser also requires passing babelOptions

### ISSUE THREAD

**Issue by DamienCassou** [mantoni/eslint_d.js#159]
Hi,

I recently switched to using [@babel/eslint-parser](https://github.com/babel/babel/tree/main/eslint/babel-eslint-parser) as eslint's parser:

`.eslintrc.js`:
```js
module.exports = {
	parser: "@babel/eslint-parser",
	parserOptions: {
		sourceType: "module",
	},
	...
}
```

This allows our project to use still-unreleased JS syntax.

Unfortunately, this also seems to break eslint_d.js. As [recommended by @aaronjensen](https://github.com/aaronjensen/eslintd-fix/issues/18#issuecomment-776084953), I had to pass `parserOptions.babelOptions` in my `.eslintrc.js` to make eslint_d.js work:

`.eslintrc.js`:
```js
module.exports = {
	parser: "@babel/eslint-parser",
	parserOptions: {
		sourceType: "module",
		babelOptions: { configFile: require.resolve("./babel.config.js") },
	},
	...
}
```

Do you know why? Is there anything you can do at the eslint_d.js level so we don't have to do that?

```
$ eslint_d --version
v7.25.0 (eslint_d v10.0.4)
```

**Comment by mantoni** [comment]
Thanks for opening an issue for this. I recall that there have been similar issues before and I'm not sure why `eslint_d` behaves differently from regular `eslint` when loading plugins or external parsers. If you have time to investigate, I'm happy to assist and review a pull request.

**Comment by mantoni** [comment]
This is probably obsolete with the new major `v14.0.0` (see #294). Should you're still having the issue, please write here and I'm happy to re-open.
