### ISSUE TITLE
--config flag is ignored

### ISSUE THREAD

**Issue by jose-elias-alvarez** [mantoni/eslint_d.js#168]
Given the following structure:

```
root/
  file-dir/
    file.js
  config-dir/
    .eslintrc.js
```

Calling `eslint_d --config config-dir/.eslintrc.js` from the root directory produces the error `Error: No ESLint configuration found in /root.` Running `eslint_d stop` before the command doesn't make a difference, and the same command with `eslint` works as expected.

It seems like the issue is caused by [this line](https://github.com/mantoni/eslint_d.js/blob/6f53734fe15d54c2de0d542732bb968f09507bd9/lib/linter.js#L75) in `translateOptionsESLint`, which attempts to assign the value of `overrideConfigFile` from the nonexistent property `cliOptions.overrideConfigFile`. Changing the right-hand side to `cliOptions.config`, which is in line with the [equivalent line](https://github.com/eslint/eslint/blob/c981fb1994cd04914042ced1980aa86b68ba7be9/lib/cli.js#L119) in ESLint's CLI code, causes the command to work properly. 

Let me know if this is the right fix and I'll put together a quick PR.

**Comment by mantoni** [comment]
TBH I never used this option myself, so I trust your thoughtful analysis. A PR would be most welcome 🙏
