### ISSUE TITLE
problem of eslint_d with vim

### ISSUE THREAD

**Issue by ruanyl** [mantoni/eslint_d.js#17]
eslint_d doesn't work with vim if `eslint` and eslint plugins like 'eslint-plugin-react' are not installed locally. While use `eslint`, the linting works even `eslint` and it's plugins are installed globally.

**Comment by mantoni** [comment]
Thanks for reporting. This might be an unintended side effect of the last feature release. Looking into it. You can try and downgrade in the meantime.

**Comment by mantoni** [comment]
Ok, so this is not a bug. `eslint_d` must be able to `require('eslint'`)`. It will always fall back to it's own dependency in case there is no local installation. Once eslint was required, it's up to eslint to load the any plugins.

I'm not sure whether I can help improve this for you. However, you could create a local symlink to your global modules with `npm link eslint-plugin-react`.

**Comment by ruanyl** [comment]
@mantoni thank your for your answer. I use `nvm` as node version manager, would this be the issue? I will try to test more.

**Comment by mantoni** [comment]
No, `nvm` shouldn't make a difference. That's fine.

**Comment by ruanyl** [comment]
A bit findings after digging into this problem.
```
➜  js-reder git:(master) ✗ eslint_d lib/generator.js
Error: Cannot find module 'eslint' from '/path/to/project/js-reader'
```
I first run this in the root dir of my project(no eslint installed locally), `eslint_d` actually not load `eslint` it has.

Then I found this line of code: https://github.com/mantoni/eslint_d.js/blob/master/lib/linter.js#L29
The dir already changed before loading `eslint`, I guess that's why it cannot find the module.

My guess:
Since the dir changed, and `eslint` is programmably used here, if `eslint-plugin-*` are not installed locally in the dir, it will throw the `cannot find module xxx` error.

**Comment by yuezk** [comment]
I have the same issue and I found that the `resolve.sync` module will not return null if module not found, instead, it will throw an error. So we should wrap it into a `try ... catch`` clause.

**Comment by mantoni** [comment]
Thanks for looking into it! I’ve published `v2.3.2` with @yuezk’s patch.
@ruanyl Can you confirm that this fixes the issue for you as well?

**Comment by ruanyl** [comment]
@mantoni, thank you @yuezk, it fixed the problem of resolving `eslint`.

**Comment by sayandcode** [comment]
For me it helped when I restarted `eslint_d` using `eslint_d restart`. This [related answer](https://github.com/mantoni/eslint_d.js/issues/21#issuecomment-158789637) helped me.
