### ISSUE TITLE
Can I stop the process when the language server is down?

### ISSUE THREAD

**Issue by EduardoAraujoB** [mantoni/eslint_d.js#170]
So, I'm having this issue
![image](https://user-images.githubusercontent.com/42449213/128379896-dd7dac2b-6910-4b13-b377-1f32274e7e92.png)
even when I'm not with my IDE and lang-server open, `eslint_d` keeps running and taking a lot of ram from my machine, but what I want to do is to stop the process when my language server is down and run it when it's up.

Is there a way to close and up `eslint_d` process? even if it's not the intention of the project to have this kind of feature, I just need a way to manually stop and run `eslint_d` and then I'll fix my problem

**Comment by mantoni** [comment]
You can call `eslint_d stop` to kill the process. The first invocation of `eslint_d` will automatically start it again. Is that what you're asking for?

**Comment by EduardoAraujoB** [comment]
yes, it is, thanks a lot
