### ISSUE TITLE
Error: Failed to load plugin declared in .eslintrc.js

### ISSUE THREAD

**Issue by icaroponce** [mantoni/eslint_d.js#171]
Hello there, 

I'm getting an error, which I don't get with `eslint`, when I have this [plugin](https://www.npmjs.com/package/eslint-plugin-formatjs) declared in my `plugins` list in the `eslintjs.rc` file

The error message: 
```
Error: Failed to load plugin 'formatjs' declared in '.eslintrc.js': Cannot find module '/home/x/y/node_modules/eslint-plugin-formatjs/node_modules/tslib/tslib.js'
```

As I mentioned, I don't get this error when using eslint, so I wonder if this could be related to eslint_d instead of the plugin itself.

eslint_d version: v7.32.0 (eslint_d v10.1.3)
eslint-plugin-formatjs version: 2.17.4

Thanks in advance.

**Comment by mantoni** [comment]
Die you try restarting `eslint_d` after configuring the plugin?

**Comment by icaroponce** [comment]
Restarting the server solved the issue.
