### ISSUE TITLE
Support Passing an Eslint Binary Path

### ISSUE THREAD

**Issue by jpulec** [mantoni/eslint_d.js#174]
Best I can tell, there's no way to specify a path for `eslint_d` to use to try to find which copy of `eslint` to run. Being able to pass in a path would be great for non-standard `eslint` setups. For example, when trying to use `eslint` with Yarn PnP, typically a patched version is used. It would be great if `eslint_d` would take a `--eslint-path` config option of some kind to support this.

Is this something that would be considered for inclusion?

**Comment by jpulec** [comment]
Finally getting a chance to dig into this...

@mantoni Best I can tell, there isn't exactly a great way to pass arguments that are only intended for the `eslint_d` daemon, which would need to get passed all the way through to the `core_d` resolution of `eslint`. One option I have working right now is using an environment variable, i.e. `ESLINTD_ESLINT_PATH` which should work fine since the whole env gets passed from the `eslintd` call to the spawned child process.

Does using an environment variable seem like a reasonable way to support a custom `eslint` binary? Or is there some better way to get args from the `eslint_d` invocation to where they are used in the child process?

**Comment by mantoni** [comment]
I can think of another option: The `args` are passed to `invoke` in the deamon here:

https://github.com/mantoni/eslint_d.js/blob/8a62b68e1dcd465697dfe98b2b14706d220010c0/lib/linter.js#L278

Then the ESLint binary is resolved relative to the `cwd` when calling `createCache`. You could check for `--eslint-path` is in the `args` there to skip resolving the binary. What do you think?

**Comment by jpulec** [comment]
Got it. Do you think `--eslint-path` should get added to the options that are parsed, and then the option parsing should happen before cache creation? Or should we just pull `--eslint-path` off `args`, if it exists, before options parsing?

**Comment by mantoni** [comment]
I have no opinion about this. Your guess is as good as mine.
