### ISSUE TITLE
Older version of `eslint` with `v11.1`

### ISSUE THREAD

**Issue by numToStr** [mantoni/eslint_d.js#176]
I just updated to `v11.1.0` which supposed to include the `v8` of `eslint` but the bundled `eslint` version is still at `v7.32.0`. Is this expected?

```
$ eslint_d --version
v7.32.0 (eslint_d v11.1.0)
```

**Comment by mantoni** [comment]
Yes. The `v11` major included support for the eslint `v8.beta`, but kept `v7` as the "bundled" eslint version. With `v11.1` the test cases pass against `v8.0.x`. Changing the default `eslint` should be done with another major release.

Is this blocking you in any way?

**Comment by numToStr** [comment]
> Is this blocking you in any way?

No, obviously not. I thought it got missed somehow.

> Changing the default eslint should be done with another major release.

Yeah, you are right. I'll wait for another release as I am still on v7 :)
