### ISSUE TITLE
--eslint-path requires specific formatting

### ISSUE THREAD

**Issue by shannonmoeller** [mantoni/eslint_d.js#177]
In trying to get `eslint_d` working with [vim-ale](https://github.com/dense-analysis/ale) and [yarn pnp sdks](https://yarnpkg.com/getting-started/editor-sdks), I found a rather unfortunate gotcha in how `--eslint-path` (introduced in #175) is handled.

The path is being parsed by both `optionator` and directly in the `linter.js` file. The path parsed by `optionator` handles all of the CLI forms you'd expect (`--eslint-path [path]`, `--eslint-path "[path]"`, `--eslint-path=[path]`, `--eslint-path="[path]"`, etc.), but the version in `linter.js` requires that you use `=` and do _not_ use quotes of any kind (`--eslint-path=path` only).

I'd love to see these lines updated to use the path as parsed by `optionator` so all of the forms are supported:

https://github.com/mantoni/eslint_d.js/blob/d638aa653960b7003414a46fca48fd704c8b8737/lib/linter.js#L281-L288

For anyone arriving here from google, this is the configuration I have in my `.vimrc` that gets `eslint_d`, vim-ale, and yarn pnp sdks working together properly:

```vim
let s:sdks = finddir('.yarn/sdks', ';')
if !empty(s:sdks)
  let g:ale_fixers = { 'javascript': ['eslint'] }
  let g:ale_linters = { 'javascript': ['eslint'] }
  let g:ale_javascript_eslint_use_global = 1
  let g:ale_javascript_eslint_executable = 'eslint_d'
  let g:ale_javascript_eslint_options = '--eslint-path=' . s:sdks . '/eslint/lib/api.js'
endif
```

**Comment by mantoni** [comment]
Would you care to send a PR to improve this?

**Comment by shannonmoeller** [comment]
Sure. Looks like the biggest hurdle here is a chicken-and-egg problem given `optionator` is intentionally unforgiving. We have to parse the args in order to see which set of args to parse. PR soon.
