### ISSUE TITLE
Feature: only use local cmd

### ISSUE THREAD

**Issue by sQVe** [mantoni/eslint_d.js#180]
👋🏼,

In my setup it would be preferable to be able to disable the global fallback of `eslint`. If there's no local `eslint` I do not want to run `eslint_d` on a file.

Is this something that is already possible or something that we could implement? 🙏🏼

**Comment by mantoni** [comment]
Hey. This is currently not possible, but could be implemented of cause. Although I'd like to learn about the circumstances when this would be relevant. Can you elaborate?

**Comment by sQVe** [comment]
If I haven't installed `eslint` locally I do not want to run `eslint` for that project. Currently it falls back to the global version, provided by `eslint_d`, which is problematic since it then also tries to resolve a config, stealing minor performance but most importantly indicating an error in my buffers (running **neovim**) with `No ESLint configuration found in...` - which is totally irrelevant information since I don't even want it to run.

**Comment by mantoni** [comment]
Ah, I understand. To me it sounds like your editor shouldn't attempt to lint the file in this situation. I'm personally using ale in vim with `eslint_d` configured as the ESLint executable and I don't seem to have this issue.

Anyway, even if we would add a flag to skip falling back to the default linter, `eslint_d` would still run unnecessarily and steal some memory. I'm also wondering if it would be wise to silently return with status code zero in this case.

I'm not against adding this feature, but I think it's worth checking if you can achieve what you want in a better way with an editor config tweak.

**Comment by sQVe** [comment]
The problem with relying on solving this on the editor end is that `eslint` config resolving is very complex. Multiple different files, recursively searched from the file being linted. It's even possible to set `eslintConfig` in the `package.json`. I would be extremely surprised if `ale` properly resolves the config.

I'm running `eslint_d` with `null-ls` + ` neovim`. It's highly configurable but it's not possible to cover all config resolving scenarios in a good way. 

I've in the past asked for a similar feature in `prettierd` and this is how it was implemented: https://github.com/fsouza/prettierd/pull/250

**Comment by sQVe** [comment]
I'm going to write a `lua` helper function to resolve the `root_path` for `eslint_d` and only run it when a config is found. It's sadly not going to cover the case of having a `eslintConfig` in `package.json`, but that's something I can live with.

It's a lot easier to resolve the binary compared to the config though, so it would still be great if this feature could be considered and implemented.

**Comment by mantoni** [comment]
Thanks for the explanation and the link to the prettier issue. I like the idea of doing this with an environment variable instead of an option.

Would you be able to send a PR for this?

**Comment by sQVe** [comment]
Sure, no problem. I'll try to get it done soonish - adding it to my forever increasing TODO list 😉

**Comment by mantoni** [comment]
Closing as resolved in `v12.1.0`.

**Comment by itsramiel** [comment]
@sQVe I am also using neovim with null-ls and enslint_d. I am getting the `Error: no eslint configuration found in ....`.

Here is my null-ls config: 
```
null_ls.setup({
  sources = {
    null_ls.builtins.formatting.prettierd,
    null_ls.builtins.diagnostics.eslint_d,
  },
})
```

How can I change it to include the changed you made here to disable it when there is no config?

**Comment by sQVe** [comment]
@itsramiel For sure, no problem. I'll can walk you through my setup. I just need to lick my wounds today. I'll get back to you early next week.

**Comment by itsramiel** [comment]
> @itsramiel For sure, no problem. I can walk you through my setup. I just need to lick my wounds today. I'll get back to you early next week.

Actually I went through your dotfiles 👀 and managed my way through it 😅
