### ISSUE TITLE
Start multiple servers

### ISSUE THREAD

**Issue by gajus** [mantoni/eslint_d.js#181]
I am trying to hack together ESLint parallelization.

The idea is:

* start 4 eslint_d servers
* index all files in the project
* use `parallel` to split eslint tasks between 4 workers

Is there a way to start 4 separate instances?

**Comment by gajus** [comment]
It looks like I could achieve this if this library allowed to override `CORE_D_DOTFILE` and `CORE_D_TITLE` env variables.

**Comment by mantoni** [comment]
I guess you could alternatively make a new tool based on [core_d](https://www.npmjs.com/package/core_d), no?

**Comment by gajus** [comment]
After familiarizing more with the codebase, that makes the most sense.
