### ISSUE TITLE
Check hash of stat_files rather than mtime

### ISSUE THREAD

**Issue by daradermody** [mantoni/eslint_d.js#186]
As part of #93, clearing the cache was introduced to automatically take into account updates to dependencies that might affect it, and mtime [was chosen instead](https://github.com/mantoni/eslint_d.js/issues/93#issuecomment-415326772) of getting the hash of `package.json` (and other files) becuase it is a bit faster.

I'd like to raise the discussion again specifically for the case of [lint-staged](https://github.com/okonet/lint-staged), which runs a git stash as a backup mechanism in case of failures, which updates the mtime of changed files. I noticed when using lint-staged with eslint_d, the cache is cleared before running every time I attempt a commit, which makes this workflow take unnecessarily long.

That said, this is a specific case where `package.json` is changed _and_ there are lint issues that prevent the commit from going through. I commit, it fails, I fix lint issues, I commit, it fails, I fix some more; every commit takes a while even though `package.json` hasn't changed since the last run (but the mtime is updated because of lint-staged's backup mechanism).

Is this case enough to justify switching to hash?

**Comment by mantoni** [comment]
Absolutely. I guess we would've opted for hashing immediately if there was a good example where mtime is not doing the right thing. Now that you provided one, I'd be happy to switch.

Care to send a PR?
