### ISSUE TITLE
Eslint 8

### ISSUE THREAD

**Issue by azuline** [mantoni/eslint_d.js#191]
Is Eslint 8 supported in any form? Can I do anything to add support if not?

**Comment by azuline** [comment]
Is the README out of date? It states

> As of v7.2.0, you can use eslint_d with multiple projects depending on different versions of eslint. Supported versions are 4.0+, 5.0+, 6.0+ and 7.0+.

**Comment by mantoni** [comment]
You're right! That section is out of date. In the compatibility notes at the bottom of the readme v8 is mentioned, but not here. Care to fix it? 🙏
