### ISSUE TITLE
eslint_d task always running

### ISSUE THREAD

**Issue by amadeus** [mantoni/eslint_d.js#199]
I currently use eslint_d via Ale, and something I've noticed is that after Vim has been fully shut down, the eslint_d process is still always left running.

I can understand it running constantly while my editor is opened, but I feel like it should close when I shut down my editor.

**Comment by mantoni** [comment]
This is by design. You could call `eslint_d stop` when leaving vim. Maybe `:help VimLeave` is a way to do this?
