### ISSUE TITLE
Add support of eslint options

### ISSUE THREAD

**Issue by roadhump** [mantoni/eslint_d.js#2]
It would be nice to have all possible options of `eslint` in `eslint_d` call: `config`, `format`, `no-ignore`, etc.

E.g

```
eslint_d lint --config some/config file.js
```

**Comment by sonnyp** [comment]
@mantoni @roadhump added eslint_d support to https://github.com/roadhump/SublimeLinter-eslint

Following up

> If you're using eslint_d in any other editor, please tell me!

From https://github.com/mantoni/eslint_d.js#editor-integration

**Comment by mantoni** [comment]
@sonnyp Noted integration in readme. Thanks a lot!
@roadhump I'm looking into options support right now.

**Comment by mantoni** [comment]
So, `eslint_d` now supports (almost) all the options, but I decided to align the default reporter with eslint and remove the need to pass the `lint` command. Therefore it's a 2.0.0 release. It feels a lot more natural to use `eslint_d` just like `eslint`.

Please check the `CHANGES.md` file for details. Sorry for the extra overhead.

**Comment by sonnyp** [comment]
@mantoni nice!
