### ISSUE TITLE
Feature Request: Configurable max instances

### ISSUE THREAD

**Issue by connorgmeehan** [mantoni/eslint_d.js#201]
I would like to be able to reduce the number of instances eslint_d keeps in memory.  Currently eslint_d is using 1.3gb of memory with all 10 instances cached.  Rather than eslint_d restarting regularly it'd be nice to be able to reduce this to 3-4 instances.

A way of configuring this could be via environment variables
```
export ESLINT_D_MAX_INSTANCES=5
eslint_d ./file.js
```

**Comment by mantoni** [comment]
That makes sense. Would you care to send a PR to implement this?

**Comment by connorgmeehan** [comment]
Yep I can PR this, I'm noticing there's some references to `CORE_D_TITLE` should I copy this in the env variable and call it `CORE_D_MAX_INSTANCES`?

Are there any knock-on effects for testing?

**Comment by mantoni** [comment]
Great! I think it should be called `ESLINT_D_MAX_INSTANCES` because the cache is implemented here. You can see examples for testing in `eslint-path-test`.

**Comment by connorgmeehan** [comment]
I've made the changes + added some error checking for invalid inputs but I'm having some trouble testing it.  I've never developed a node CLI package before.  What's the best way to run my branch of eslint_d on my machine.  I've tried `yarn global add "file:$PWD"` and `npm link`.

**Comment by mantoni** [comment]
This has been addressed with the new major `v14.0.0` (see #294). The is a separate daemon instance per eslint installation now, and you can control when each of them terminates, either after IDLE time (`ESLINT_D_IDLE`), or when the parent process exits (`ESLINT_D_PPID`).
