### ISSUE TITLE
Replace `SublimeLinter-contrib-eslint_d` with `SublimeLinter-eslint` in `README.md`

### ISSUE THREAD

**Issue by tukusejssirs** [mantoni/eslint_d.js#205]
I noticed you suggest to use [SublimeLinter-contrib-eslint_d](https://github.com/roadhump/SublimeLinter-contrib-eslint_d) in Sublime Text. That package does not seem to be maintained anymore.

In [SublimeLinter-eslint v4.3](https://github.com/SublimeLinter/SublimeLinter-eslint/releases/tag/4.3.0), thay use `eslint_d` when available.

Could you suggest to use SublimeLinter-eslint instead?

Thanks for awesome package! I have just learned about `eslint_d` (from the SL-eslint release notes), but it seems to be awesome at speed and resource usage. :pray:

**Comment by mantoni** [comment]
Absolutely. The change to the plug-in to support eslint_d is a recent change. I agree that it should be noted in the readme. I'm not using Sublime myself, so I'd rather let someone document it who knows how to use it.

Would you care to send a PR for that? 🙏

**Comment by mantoni** [comment]
Fixed in #209.
