### ISSUE TITLE
Not reading the right config files

### ISSUE THREAD

**Issue by simonzack** [mantoni/eslint_d.js#21]
I have a `.eslintrc.json` in my home directory and a `package.json` in my project directory with eslint configs, but when running `eslint_d test.js` for some file in the project directory eslint_d ignores `package.json` and proceeds to use the config from the home directory. `eslint` doesn't have this problem.

**Comment by mantoni** [comment]
Config file reading is done by eslint. If you updated eslint recently, make sure to restart eslint_d with `eslint_d restart`.

**Comment by simonzack** [comment]
Actually I discovered and installed eslint eslint_d and the sublime plugin all just today. So that can't be the issue can it?

**Comment by mantoni** [comment]
Hm, then it doesn't sound like the issue, indeed. If you could help looking into the issue, that'd be rad. It might take some time for me right now.

**Comment by mantoni** [comment]
In the meantime, I learned that .eslintrc files take precedence over package.json files in the same directory. Can you check whether this is also the case here?

**Comment by eipark** [comment]
I have an `.eslintrc` in my project and when running `eslint` without `eslint_d` it uses those rules fine, but when I turn on `eslint_d` it seems to ignore it. I've tried using the `-c` flag and seeing what `--no-eslintrc` does but no change.

**Comment by mantoni** [comment]
@eipark  Can you describe your setup in more detail? I’m using `.eslintrc` files as well and everything works fine.

**Comment by eipark** [comment]
Sure. My `.vimrc` looks as sucH

```
" syntastic
set statusline+=%#warningmsg#
set statusline+=%{SyntasticStatuslineFlag()}
set statusline+=%*

let g:syntastic_always_populate_loc_list = 1
let g:syntastic_auto_loc_list = 1
let g:syntastic_check_on_open = 0
let g:syntastic_check_on_wq = 1
let g:syntastic_javascript_checkers = ['eslint']

let g:syntastic_javascript_eslint_exec = 'eslint_d'
```

I have a project `~/my/project`, which has `~/my/project/.eslintrc`. In `~/my/project/` I run `eslint_d start` and then I open vim. It indeed lints files, but it doesn't have any of the rules from my `.eslintrc`. 

I've tried specifying it explicitly with `--config` and other things but no dice.

**Comment by mantoni** [comment]
Thanks. Some more questions: Which version of eslint_d do you have? Is there a local install of eslint in your project? If so, which version?

Also: Can you try `eslint_d stop` and then `eslint_d .` to make sure it loaded freshly?

**Comment by eipark** [comment]
```
 ♥  eslint_d --version
v2.4.0 (eslint_d v3.1.0)
[02:20 PM] [epark@BOSMM2PG37YFVH8] [~]
 ♥  which eslint_d
/usr/local/bin/eslint_d

```

**Comment by osdiab** [comment]
I'm having similar problems, hopefully this helps:

```
╭─osdiab@Omars-MBP  ~/opensource/components  ‹confirmation-button*›
╰─$ eslint_d stop
Not running
╭─osdiab@Omars-MBP  ~/opensource/components  ‹confirmation-button*›
╰─$ eslint_d src/ConfirmationButton/ConfirmationButton.jsx
eslint %                                                                                                              ╭─osdiab@Omars-MBP  ~/opensource/components  ‹confirmation-button*›
╰─$ eslint src/ConfirmationButton/ConfirmationButton.jsx

/Users/osdiab/opensource/components/src/ConfirmationButton/ConfirmationButton.jsx
  45:21  error  Property should be placed on a new line  react/jsx-first-prop-new-line
  45:57  error  Property should be placed on a new line  react/jsx-first-prop-new-line

✖ 2 problems (2 errors, 0 warnings)

╭─osdiab@Omars-MBP  ~/opensource/components  ‹confirmation-button*›
╰─$ eslint_d --version                                                                                            1 ↵
esv2.8.0 (eslint_d v3.1.0)
╭─osdiab@Omars-MBP  ~/opensource/components  ‹confirmation-button*›
╰─$ eslint --version
v2.8.0
╭─osdiab@Omars-MBP  ~/opensource/components  ‹confirmation-button*›
╰─$ which eslint_d
/Users/osdiab/.nvm/versions/node/v5.7.1/bin/eslint_d
╭─osdiab@Omars-MBP  ~/opensource/components  ‹confirmation-button*›
╰─$ which eslint
/Users/osdiab/.nvm/versions/node/v5.7.1/bin/eslint
```

**Comment by marcelbeumer** [comment]
Same here. Works fine with eslint version 2.9.0, doesn't work with eslint@latest (now 2.10.1), eslint_d v3.1.0

**Comment by iansinnott** [comment]
I'm also seeing this issue. I resolved it by being explicit about using `bable-eslint` as the parser. On the CLI:

```
eslint_d --parser=babel-eslint src/
```

Ideally the parser should be read from the local `.eslintrc` file, which in this case it wasn't. But being explicit about the parser might resolve some peoples issues for the time being.

For anyone using Syntastic, this can be configured by adding the following to your `.vimrc`:

```vim
let g:syntastic_javascript_eslint_args = '--parser=babel-eslint'
```

**Comment by gkrcode** [comment]
Had same issue iansinnott's solution fixed it. Thanks @iansinnott.

**Comment by mantoni** [comment]
`eslint_d` `3.1.1` was just released which addresses this issue. Can anyone confirm?

**Comment by mkitt** [comment]
`3.1.1` is working again for me. 👍

**Comment by sayandcode** [comment]
> Config file reading is done by eslint. If you updated eslint recently, make sure to restart eslint_d with `eslint_d restart`.

This helped me 5 years later. Thanks a lot dude!

**Comment by sayandcode** [comment]
> Config file reading is done by eslint. If you updated eslint recently, make sure to restart eslint_d with `eslint_d restart`.

This helped me 5 years later. Thanks a lot dude!

**Comment by sayandcode** [comment]
> Config file reading is done by eslint. If you updated eslint recently, make sure to restart eslint_d with `eslint_d restart`.

@mantoni This helped me 5 years later. eslint_d wasn't picking up the airbnb-config. Thanks a lot dude!
