### ISSUE TITLE
Failed to load plugin 'react' declared in '.eslintrc.json

### ISSUE THREAD

**Issue by calwritescode** [mantoni/eslint_d.js#210]
If I lint any file containing an import from `'react'` in my project using `eslint_d` I get the following error

```
❯ eslint_d src/pages/index.tsx
Error: Failed to load plugin 'react' declared in '.eslintrc.json 
» eslint-config-next/core-web-vitals 
» /Users/cal/Code/blog/node_modules/.pnpm/eslint-config-next@12.2.3_b5e7v2qnwxfo6hmiq56u52mz3e/node_modules/eslint-config-next/index.js': 
ENOENT: no such file or directory, open '/Users/cal/Code/blog/node_modules/.pnpm/object.assign@4.1.2/node_modules/object.assign/index.js'
Referenced from: /Users/cal/Code/blog/node_modules/.pnpm/eslint-config-next@12.2.3_b5e7v2qnwxfo6hmiq56u52mz3e/node_modules/eslint-config-next/index.js
```

When I use `npx eslint <file>` on the same file it runs w/o any errors, hence I don't think it's an issue with the way my project is set up. I am using `pnpm` as package manager.

To check if the problem is due to the usage of `pnpm` I copied the project and install all packages using npm which leads to the following error:

```
❯ eslint_d src/pages/index.tsx
Error: Failed to load plugin 'react' declared in '.eslintrc.json » eslint-config-next/core-web-vitals » /Users/cal/Code/test/node_modules/eslint-config-next/index.js': ENOENT: no such file or directory, open '/Users/cal/Code/blog/node_modules/.pnpm/object.assign@4.1.2/node_modules/object.assign/index.js'
Referenced from: /Users/cal/Code/test/node_modules/eslint-config-next/index.js
```

Is there a workaround/fix for that?

**Comment by mantoni** [comment]
Did you try `eslint_d restart`?

**Comment by calwritescode** [comment]
just now I did and it actually fixed the problem. Thanks a lot! I really could've thought about trying that myself.. I am still a bit confused why this error occurred. It worked perfectly fine in a different react project..

**Comment by mantoni** [comment]
No worries. This sometimes happens when configs or transitive dependencies change.
