### ISSUE TITLE
Neovim lsp diagnosis will flicker when `%!eslint_d --stdin --fix-to-stdout --stdin-filename %`

### ISSUE THREAD

**Issue by ShiChenCong** [mantoni/eslint_d.js#211]
Hi there, Thank you  for the work for fast eslint_d
I add auto fix lint error when save, but will flicker like this 
![Aug-27-2022 17-03-11](https://user-images.githubusercontent.com/22486446/187024690-6e48f1a2-59f0-41bc-87b9-419bf4cc8486.gif)
screenshot:
![image](https://user-images.githubusercontent.com/22486446/187024802-87a71c73-5381-401c-86d3-c07cf2c4d994.png)

**Comment by mantoni** [comment]
I'm not sure if there is anything `eslint_d` could do to improve the situation.
