### ISSUE TITLE
Problem with global installed eslint

### ISSUE THREAD

**Issue by ruanyl** [mantoni/eslint_d.js#22]
Hi, I still the problem of `eslint` which is installed globally. Currently, if eslint_d cannot found `eslint` under working dir, it will load the `eslint` which installed under `eslint_d`.

Everything works just fine until I need to load `eslint-plugin-*`. these plugins are installed globally also. And they are loaded by `eslint`. 

`eslint` seems not looking for global `plugins` if it's installed and loaded as a local module. An issue may relevant to this: https://github.com/eslint/eslint/issues/4472

I am just thinking that would it makes more sense for `eslint_d` to load global `eslint` instead of local `eslint` under `eslint_d`?

I made a small change to the way of loading `eslint`, and I tested it with `eslint_d cli` and `vim`. It works just fine.

I will make a pull request for this :)

**Comment by mantoni** [comment]
The issue you referred to is now resolved and there is the `cwd` option support is eslint now. It's intentional to load the local eslint install and fall back to a global one. This makes it possible to have different eslint versions in two projects.

I'm wondering whether the issue can be solved by feeding the `cwd` option to eslint. Would you be able to investigate?

**Comment by mantoni** [comment]
eslint_d 3.0.0 now passes on the `cwd` option to eslint. Can you please check if it's working for you now?

**Comment by ruanyl** [comment]
@mantoni thanks for the update! Looks like it works for me :+1:

**Comment by mantoni** [comment]
The resolve mechanics didn't change.

**Comment by jstejada** [comment]
Hi @mantoni , the `cwd` option is not working for me. When I try to run it I get: 

`Error: Invalid option '--cwd' - perhaps you meant '-c'?`

Am I missing something?
Thanks!

**Comment by mantoni** [comment]
The `cwd` option is set to your current directory and passed to the eslint API. It's not a command line option.
