### ISSUE TITLE
Run in background when my Terminal is off

### ISSUE THREAD

**Issue by Natchii59** [mantoni/eslint_d.js#220]
**Hello 👋🏻**
My eslint_d is running in background while my terminal is off.
I have last version in Neovim, and I use lsp, lspsaga, mason for eslint_d.

I would like to turn off eslint_d when neovim or my terminal is off.

<img width="1370" alt="image" src="https://user-images.githubusercontent.com/96394660/195623469-10bd6493-0dab-495c-9313-703c08735a0c.png">

**Comment by mantoni** [comment]
You can stop the background process with `eslint_d stop`. You will have to find a way to invoke this command when your terminal is closed.
