### ISSUE TITLE
Failed to load parser with eslint_d

### ISSUE THREAD

**Issue by PaulKushch** [mantoni/eslint_d.js#221]
Hi!

I started getting this error for all imports with `eslint_d` version `12.2.1` (in tsx/js files):

![image](https://user-images.githubusercontent.com/5386035/197363733-0dd1829c-86fe-40a8-9ac0-3d6f1a15b334.png)

Anyone else having the same issue and maybe some solution?

Best regards

**Comment by mantoni** [comment]
Die you try `eslint_d restart` already?

**Comment by PaulKushch** [comment]
@mantoni I use neovim `(Astronvim)` and dont know if it is possible to reload that way?

When I source luafile (`:luafile %`) I get that error with eslint_d while doing a standard import (but `eslint-lsp` works fine):
![image](https://user-images.githubusercontent.com/5386035/197416383-288aacac-6955-46f4-98b4-6e3314e3ca10.png)

**Comment by mantoni** [comment]
You can run `eslint_d restart` from your command line. It will kill and relaunch the daemon process. It usually fixes issues around parser loading.

**Comment by Nargonath** [comment]
I had a totally unrelated problem as well. Eslint_d couldn't load some internals dependencies of `eslint-config-next` something in the vein of `cannot load plugin: @next/next`. Just in case something find his way into this issue as well, `eslint_d restart` did the job and fixed the problem.

Thanks @mantoni.

**Comment by mantoni** [comment]
This is probably obsolete with the new major `v14.0.0` (see #294). Should you're still having the issue, please write here and I'm happy to re-open.
