### ISSUE TITLE
Publish to Homebrew?

### ISSUE THREAD

**Issue by lougreenwood** [mantoni/eslint_d.js#234]
Yarn 2 / 3 don't support installing using globals. For those of us Mac users who use Yarn and not NPM, do you have any plans to instead publish the project on Homebrew so we can install from that source instead?

Thanks!

**Comment by mantoni** [comment]
I have no experience publishing anything to homebrew. Would you be able to assist with setting this up? And most importantly, can you contribute a script that automates the publishing process?

**Comment by OJFord** [comment]
>  And most importantly, can you contribute a script that automates the publishing process?

Brew has its own mechanism for that aiui. See for example: https://github.com/Homebrew/homebrew-core/pull/168123

The formulae also needn't be (I would say typically aren't) contributed/maintained by the project's author, someone just needs to do it (a PR to homebrew-core) and if it's acceptable (not just the code there but e.g. the project has enough stars, eslint_d does) then it's in. I might get to it later.

**Comment by lishaduck** [comment]
Noticed this project while running `brew outdated`. I think this can be closed as of Homebrew/homebrew-core#198311.
