### ISSUE TITLE
Doesn't load config when using `--fix-to-stdout` option

### ISSUE THREAD

**Issue by itaranto** [mantoni/eslint_d.js#237]
Running `eslint_d --fix-to-stdout --stdin < some_file.js` shows errors that are ingored by my `.eslintrc.js` config while `eslint_d --fix some_file.js` doesn't.

Is there any way to print a debug message to validate if `eslint_d` is actually reading the config file?

**Comment by mantoni** [comment]
There's a pending issue for this feature: #87

**Comment by mantoni** [comment]
Unfortunately the `--fix-to-stdout` option had to be removed with `v14.0.0` and I'm not intending to bring this back due to the way the new implementation works. Sorry.
