### ISSUE TITLE
Bug with plugin

### ISSUE THREAD

**Issue by Bogdan-Torkhov** [mantoni/eslint_d.js#239]
Have these bug:  Error: Failed to load plugin '@typescript-eslint' declared in '.eslintrc.json': Cannot find module '@typescript-eslint/eslint-plugin'

**Comment by mantoni** [comment]
Usually this kind of error can be fixed with `eslint_d restart`. Have you tried?

**Comment by serranomorante** [comment]
> Usually this kind of error can be fixed with `eslint_d restart`. Have you tried?

Amazing!

I had to use `:terminal eslint_d restart` from inside neovim.

Why does that worked?

**Comment by camin-mccluskey** [comment]
Not sure how common this issue is but I trip over it every single time I create a new Typescript project, leading to erroneous debugging of my eslint config.  Might it be worth have a line in the README that calls out the necessity of restarting `eslint_d` on this error?

**Comment by mantoni** [comment]
@camin-mccluskey It's actually mentioned here: https://github.com/mantoni/eslint_d.js#what-if-eslint-or-a-plugin-is-updated. If you have ideas how to make that more clear, please feel free to suggest.

**Comment by camin-mccluskey** [comment]
Ah my bad! No this looks fine, I _guess_ it would be helpful to explicit call out the error above but I appreciate it won't be the same for everyone using eslint_d. Happy to leave as is and hope this issues gets prioritised on Google for this error

**Comment by peterpme** [comment]
@Bogdan-Torkhov do you mind renaming this issue to: `failed to load plugin '@typescript-eslint' declared in` so that when folks look through the issues, this one comes up?

Thank you!

**Comment by mantoni** [comment]
This is probably obsolete with the new major `v14.0.0` (see #294). Should you're still having the issue, please write here and I'm happy to re-open.
