### ISSUE TITLE
eslint_d looks for /conf/eslint-recommended.js

### ISSUE THREAD

**Issue by shot-codes** [mantoni/eslint_d.js#243]
I have a `.eslintrc.cjs` as seen below. When I run eslint_d on any file in my project I get the following error:
```
Error: ENOENT: no such file or directory, open '/Users/user/project/node_modules/.pnpm/eslint@8.33.0/node_modules/eslint/conf/eslint-recommended.js'
Referenced from: /Users/user/project/.eslintrc.cjs
```
I believe eslint-reccomended.js was present in /conf/ in older versions of eslint,but no longer. Any help with this would be greatly appreciated.

```js
// .eslintrc.cjs
module.exports = {
  root: true,
  parser: "@typescript-eslint/parser",
  extends: ["eslint:recommended", "plugin:@typescript-eslint/recommended", "prettier"],
  plugins: ["svelte3", "@typescript-eslint"],
  ignorePatterns: ["*.cjs"],
  overrides: [{ files: ["*.svelte"], processor: "svelte3/svelte3" }],
  settings: {
    "svelte3/typescript": () => require("typescript"),
  },
  parserOptions: {
    sourceType: "module",
    ecmaVersion: 2020,
  },
  env: {
    browser: true,
    es2017: true,
    node: true,
  },
};
```

**Comment by mantoni** [comment]
It is not `eslint_d` trying to load `eslint/conf/eslint-recommended.js` here, it is `eslint`. Maybe this is a cache invalidation issue and `eslint_d restart` helps?

If this is still an issue after restarting, and it works as expected with `eslint` itself, please try to narrow down the issue, ideally post something that allows me to reproduce. Thanks.

**Comment by shot-codes** [comment]
`eslint_d restart` did in fact resolve the issue. Feel a little silly for asking before trying now XD regardless, thank you
