### ISSUE TITLE
Start server using compact format

### ISSUE THREAD

**Issue by ruyadorno** [mantoni/eslint_d.js#25]
Hi @mantoni, first of all, many thanks for the brilliant work on `eslint_d` :blush: 

I have stumbled upon an issue when working on [eslintme](https://github.com/ruyadorno/eslintme) that is the default value for the `format` option. The problem is that **vim** and probably other editors will expect a non-styled output, e.g. `compact` format. 

To work around that limitation, my quick n'dirt solution was to point to a forked branch that replaces the default value of the compact option, as you can see here: https://github.com/ruyadorno/eslint_d.js/commit/f7d4746fb7188a204e380f15162aeb5df5215a54

While the solution is working well for me, I don't feel like it's a proper solution in the long term. What I think would be a much better solution is to add the format option to `eslint_d start` command and store this value for every subsequent linting.

I would like to hear your thoughts about it, is it something that you would like to see on `eslint_d`? Would you be open to merge a PR introducing these changes? There could be better ways to achieve the same functionality?

sorry for the long message :sweat_smile: thanks again!

**Comment by mantoni** [comment]
I'd prefer the defaults to stay the same as eslint. I'm using vim myself and I've seen that [syntastic passes the compact format as an option](https://github.com/scrooloose/syntastic/blob/master/syntax_checkers/javascript/eslint.vim#L45).

You could to the same thing by passing the `-f compact` option through via netcat, but you'd have to use the "internal" JSON protocol:

```bash
echo '{"cwd":".","args":["-f","compact","./lib/*.js"]}' \
  | nc localhost `cat ~/.eslint_d_port`
```

We could document the protocol in the README to make part of the `eslint_d` API so that we're not breaking it without bumping the major.

What do you think?

**Comment by ruyadorno** [comment]
wow, that's awesome :confetti_ball:

this completely fixes the issue for my usecase :blush: I think it would be nice to document it so people know they can use it.

Many thanks :+1:

**Comment by volkanunsal** [comment]
@mantoni Is it possible to add more documentation on how this hack works? Currently when I run this

```bash
echo "$TOKEN $PWD file.js" | nc localhost $PORT
```

I see no feedback in my console. How do I know it's working?

**Comment by mantoni** [comment]
Yeah, this could be documented better. It's basically the "internal" protocol that `eslint_d` uses.

If the execution is successful and eslint does not produce any output, this command will also not produce any output. The easiest way to test the invocation is to violate one of your eslint rules in `file.js` and then run the command. If you still don't get any output, there is something wrong.

**Comment by volkanunsal** [comment]
@mantoni Thanks for the tip. I didn't realize file.js was the file to lint. Now I have it working, but it seems to  give a warning regarding ignore patterns that I couldn't figure out how to squash.

```bash
  0:0  warning  File ignored because of a matching ignore pattern. Use "--no-ignore" to override
```

Here is my one-liner:

```bash
find ./assets -type f -name "*.js" | xargs echo "$TOKEN $PWD --cache %n" | nc localhost $PORT
```

**Comment by mantoni** [comment]
This warning comes from `eslint`. Check if the same occurs if you invoke eslint with the files found by `find`. Oh, and instead of using `find`, you can pass a glob expression to eslint, like `./assets/*.js`.

**Comment by volkanunsal** [comment]
@mantoni I tried eslint's globs, but it doesn't seem to respect the ignorefile, event when I specify it in arguments.

```bash
echo "$TOKEN $PWD --cache --ignore-path ./.eslintignore ./assets/**/*.js" | nc localhost $PORT
```

So I came up with a more complicated one-liner that parses `.eslintignore` to let the `find` command to know which patterns to ignore.

```bash
#!/bin/bash
#
# Uses eslint_d's network interface to lint js files.
#
# Arguments
#   $0 - this script
#   $1 - path of the assets folder. Default: './assets'

PORT=`cat ~/.eslint_d | cut -d" " -f1`
TOKEN=`cat ~/.eslint_d | cut -d" " -f2`
DIRPATH=${1:-./assets}

eval $(cat .eslintignore | xargs | awk '{ split($0, parts); args=""; for(key in parts) {args = args " -and -not -path \"" parts[key] "\"";}; print "find $DIRPATH -type f -name \"*.js\"" args }') | xargs echo "$TOKEN $PWD --cache %n" | nc localhost $PORT
```

**Comment by aaronjensen** [comment]
Maybe a silly question, but have you tried:

```bash
echo "$TOKEN $PWD --cache ." | nc localhost $PORT
```

The args are the same as `eslint`, so however you run `eslint`, that's what you put after the `$PWD`

**Comment by mantoni** [comment]
Goot point @aaronjensen. Also, did you try the `--ignore-path` after a fresh `eslint_d restart`? It might have cached settings that where passed in by any of your previous attempts.

**Comment by volkanunsal** [comment]
@aaronjensen Yup, tried that. I also tried restarting the server a couple of times, but nothing worked except the approach above. :-/
