### ISSUE TITLE
eslint_d causes an error because I have spaces in my windows username.

### ISSUE THREAD

**Issue by kubamus** [mantoni/eslint_d.js#263]
Hi! The problem is that I have a windows user whose name is, for example, "Kuba X", the problem is in this space. Eslint shows me an error: `'C:\Users\Kuba' is not recognized as an internal or external command, operable program or batch file.`. I have custom neovim config. I use packer. Eslint is installed with Mason. This config is from a video by youtuber Josean Martinez called "How I Setup Neovim On My Mac To Make It Amazing - Complete Guide". Anyone know how to fix this error? After disabling eslint, this problem disappears, but I need eslint. 
Do you know how to fix this error?

**Comment by mantoni** [comment]
Thanks for reporting. Can you please check if this was fixed with #280 in `v13.1.1`?

**Comment by mantoni** [comment]
This is probably obsolete with the new major `v14.0.0` (see #294). Should you're still having the issue, please write here and I'm happy to re-open.
