### ISSUE TITLE
The process doesn't terminate

### ISSUE THREAD

**Issue by wr9dg17** [mantoni/eslint_d.js#279]
Hi! I'm using `eslint_d` in my neovim config. As linting plugin I'm using [mfussenegger/nvim-lint](https://github.com/mfussenegger/nvim-lint). It works great and fast but I recognized that even after exiting neovim and closing terminal I can see `eslint_d` process still hanging in system monitoring. After switching to `eslint` (not eslint_d) I can see that processes terminating (as they should) after exiting neovim. 

P.S. I'm using mac os

**Comment by mantoni** [comment]
This is by design. However a potential change is being discussed in #236. Please, feel free to help 🙏
