### ISSUE TITLE
Failed to load plugin using Turborepo

### ISSUE THREAD

**Issue by MaximeCap** [mantoni/eslint_d.js#286]
Hello @mantoni,
I try to configure my Nvim configuration using Conform and Eslint_d as a parser of my typescript project

I try different fixes that come from the resolved issues but nothing seems to work.

I have a monorepo using PNPM and Turbo.
The project looks like that
```
|_ packages
|        |_ shared-eslint conf
|_ apps
         |_ backend
                     |_ .eslintrc.cjs using the shared-eslint conf
```

eslint_d seems to detect the eslint configure but cannot load plugins in my case `@typescript-eslint`
![Screenshot 2024-03-06 at 11 49 23](https://github.com/mantoni/eslint_d.js/assets/35339059/d45540f1-c0d4-4ee7-8571-c134b8feee60)

**Comment by mantoni** [comment]
When you're experimenting with configs, you might need to call `eslint_d restart`. Sometimes it doesn't pick up plugin changes. Let me know if that helps.

**Comment by Karelito00** [comment]
Same here: I'm using nvim and yarn.

This has happened to me 2 times already, the packages are installed correctly and eslint_d doesn't find them, but when I rename the project folder it starts working as expected. Pretty strange.

`eslint_d: Error: Failed to load plugin 'prettier' declared in '.eslintrc.json': Cannot find module 'eslint-config-prettier'`

**Comment by mantoni** [comment]
This is probably obsolete with the new major `v14.0.0` (see #294). Should you're still having the issue, please write here and I'm happy to re-open.
