### ISSUE TITLE
Solved switching between projects with and without flat config

### ISSUE THREAD

**Issue by kommander** [mantoni/eslint_d.js#288]
I use nvim btw. Just though I'd share this here, as this was really annoying me and I spent quite some time getting it to work. I have to switch between projects with different setups and some are using the flat config already, some are not. Here's how I solved that:

In my `lint.lua` config I manually download and setup my fork branch with these two lines changes in `/bin/eslint_d.js`:

```diff
-process.env.CORE_D_TITLE = 'eslint_d';
-process.env.CORE_D_DOTFILE = '.eslint_d';
+process.env.CORE_D_TITLE = process.env.CORE_D_TITLE || 'eslint_d';
+process.env.CORE_D_DOTFILE = process.env.CORE_D_DOTFILE || '.eslint_d';
```
[> Branch is here <](https://github.com/mantoni/eslint_d.js/compare/master...kommander:eslint_d.js:override-core-d-options#diff-7cfa45a31ca8cba00cbd6507b5054b30b30d28d63fd2a3b620bf72df445c5305R23-R24)

To setup `nvim-lint`, at startup I then check for existence of `eslint.config.js` in cwd and override the env that eslint_d is called in, to get a separate daemon starting up with ESLINT_USE_FLAT_CONFIG enabled.

```lua
        local env = nil
        local cwd = vim.loop.cwd()
        local maybe_config_path = vim.fn.fnamemodify(cwd .. '/eslint.config.js', ':p')
        local has_flat_config = vim.fn.filereadable(maybe_config_path) == 1

        if has_flat_config then
          env = {
            ['ESLINT_USE_FLAT_CONFIG'] = 'true',
            ['CORE_D_TITLE'] = 'eslint_d_flat',
            ['CORE_D_DOTFILE'] = '.eslint_d_flat',
            ['PWD'] = cwd,
            ['SHELL'] = os.getenv 'SHELL',
            ['TMPDIR'] = os.getenv 'TMPDIR',
            ['HOME'] = os.getenv 'HOME',
          }
        end
```

`nvim-lint` overrides the whole env and the additional variables are needed, otherwise it just does nothing and returns nothing.
Not the prettiest solution, but easiest and works wonders for my setup and blood pressure.

Anyway this option could go into a release so I can use the toolchain without manual installs again? @mantoni 

Disclaimer: I didn't look into core_d yet and what the effect of using different daemons is here, but it works well for me and I only have the `eslint_d` and `eslint_d_flat` daemons running at all times and so far nothing got stuck on quite large projects.

**Comment by dantxal** [comment]
wish I knew how to do a manual install on nvim, using mason, still a lot to learn, gonna upvote your PR, hopefully I can get it to work soon

**Comment by kommander** [comment]
I am just manually downloading my repo with the fix if it doesn't exist when `none-ls` is loaded in the config:
```lua
    local eslint_d_repo_path = vim.fn.stdpath 'data' .. '/eslint_d_patched'
    if not vim.loop.fs_stat(eslint_d_repo_path) then
      local eslint_d_repo = 'https://github.com/kommander/eslint_d.js'
      vim.fn.system { 'git', 'clone', '--filter=blob:none', '--branch=override-core-d-options', eslint_d_repo, eslint_d_repo_path }
      vim.fn.system { 'npm', 'install', '--prefix', eslint_d_repo_path }
    end
```
(Note: This is synchronous, so it blocks everything the first time, didn't bother making it async for now)

Then I just override the command and env in the setup (same thing can be done for the builtins in `nvim-lint`):
```lua 
    local cmd_name = vim.fn.fnamemodify(eslint_d_repo_path .. '/bin/eslint_d.js', ':p')

    null_ls.setup {
      sources = {
        require('none-ls.code_actions.eslint_d').with {
          command = cmd_name,
          env = env,
        },
        require('none-ls.diagnostics.eslint_d').with {
          command = cmd_name,
          env = env,
        },
        ...
      },
    }
```
The repo does not have to be downloaded automatically in the config like this, you can also just manually clone the repo somewhere locally and point `cmd_name` to it and then do the override. Even if my PR gets merged, one would still have to do the command and env override for whatever plugin is being used.

**Comment by mantoni** [comment]
This is probably obsolete with the new major `v14.0.0` (see #294).
