### ISSUE TITLE
eslint_d doesn't seem to show import/order warnings

### ISSUE THREAD

**Issue by DennisTheMenace780** [mantoni/eslint_d.js#290]
I'm not really familiar with the tech underpinning `eslint`, so bare with me. I use Neovim, and in particular, `None-LS. They recently introduced some changes, I had to update my Neovim config, and now when using just barebones eslint I don't see any warnings or errors in my editor. However, if I switch over to `eslint_d`, then all the sudden i'm able to see some warnings, just not all of them. 

For example, we have a custom rule that looks like this in one of the configs we extend from: 
```
  rules: {
    "import/order": [
      "error",
      {
        groups: ["builtin", "external", "internal", "index", "sibling"],
        "newlines-between": "never",
      },
    ],
```
Before my editor borked, I could always see these errors (see img from colleague), but now I simply am unable to do so. 
![image](https://github.com/mantoni/eslint_d.js/assets/99361605/a4fb3919-ee51-4254-995f-52c6b05e8948)

From what I have read, eslint seems to be what is reading the configuration for `eslint_d`, and it seems that `eslint_d` is getting _some_ kind of information, but it's clearly not getting _all_ of the information, and that is what i'm trying to figure out 🤔 

Any thoughts? Happy to provide more information, just not sure what would be the most useful at this point.

**Comment by DennisTheMenace780** [comment]
The big concern I have is that if it's not applying a simple import/order, i'm not really sure what else is not being applied :/

**Comment by johnend** [comment]
I have had a similar experience today with module resolution too. No error (NeoVim via Mason) other things work. Have had to switch to the Lsp version for the time being.

**Comment by mantoni** [comment]
This is probably obsolete with the new major `v14.0.0` (see #294). Should you're still having the issue, please write here and I'm happy to re-open.
