### ISSUE TITLE
eslint_d is not able to detect eslint configuration

### ISSUE THREAD

**Issue by shubhamku044** [mantoni/eslint_d.js#292]
eslint_d is not able to detect eslint configuration files like .mjs, .config.js etc.
it is only detecting .eslintrrc.json file but this is not deprecated

**Comment by fabiodcorreia** [comment]
I have the same issue

**Comment by mantoni** [comment]
This is probably obsolete with the new major `v14.0.0` (see #294). Should you're still having the issue, please write here and I'm happy to re-open.
