### ISSUE TITLE
Absence of --fix-to-stdout

### ISSUE THREAD

**Issue by DamienCassou** [mantoni/eslint_d.js#295]
Hi,

thank you very much for maintaining eslint_d that I heavily rely on and congratulations for v14 :fireworks:!

The previous version of eslint_d had a `--fix-to-stdout` option that [eslintd-fix](https://github.com/aaronjensen/eslintd-fix) (an Emacs package) relied on. Other tools such as [reformatter](https://github.com/purcell/emacs-reformatter) also relies on software reading from stdin and writting to stdout.

Is this feature planned to be ported to the new architecture?

**Comment by mantoni** [comment]
Yes, I had to drop that feature unfortunately. I'm not sure it's possible to do with the new architecture since eslint itself doesn't support it. If you have ideas how to do it, I'm all ears.

**Comment by DamienCassou** [comment]
eslint has a [--fix-dry-run](https://eslint.org/docs/latest/use/command-line-interface#--fix-dry-run) which can be used with `--format json` to get the fixed output without writing it.

That being said, you could also answer that this feature is out-of-scope of this project (which makes sense in my opinion).

**Comment by mantoni** [comment]
Well, it is out of scope, but it was also supported in a long series of major releases, and as you pointed out, other tools already rely on the feature.

So if it's possible without compromising on other things, I'm happy to bring it back. Or would you even care to look into sending a PR yourself? ❤️

**Comment by DamienCassou** [comment]
I created a draft PR in #298.

**Comment by amritk** [comment]
We need this one bad! Had to switch back to regular eslint for now, freezes for seconds every time I hit save!

**Comment by DamienCassou** [comment]
@mantoni I don't have much time to spend on the PR every day so feel free to do whatever you want with it if you feel the need to finish the task quickly. Otherwise, I will keep pushing small improvements regularly.
