### ISSUE TITLE
Testimony on the quality of the code

### ISSUE THREAD

**Issue by DamienCassou** [mantoni/eslint_d.js#302]
In the context of https://github.com/mantoni/eslint_d.js/issues/295 I have read most of the code of this project and I have to say it is absolutely beautiful. With barely any comment or documentation, you managed to write code that is very easy to navigate, understand and change. The things I appreciate most:

- there are many tests
- functions are small
- names of files, variables and functions are intention-revealing
- every piece of code has one and only one responsibility

Very good job!

**Comment by mantoni** [comment]
Thank you very much for the kind words. ❤️
