### ISSUE TITLE
eslint_d foramtting in none-ls not working on newest version

### ISSUE THREAD

**Issue by KRISCHOMAT** [mantoni/eslint_d.js#303]
I just updated eslint_d from Mason to the latest versions 14.0.0 and 14.0.1  and it seems that formatting in nvim did not work anymore with that. So I swichted back to 13.1.2 and formatting is up and running again.

**Comment by RayGuo-ergou** [comment]
see https://github.com/mantoni/eslint_d.js/issues/295 and https://github.com/mantoni/eslint_d.js/pull/298

**Comment by mantoni** [comment]
📦 Fix released in `v14.0.2`
