### ISSUE TITLE
Update to eslint 2.0

### ISSUE THREAD

**Issue by netei** [mantoni/eslint_d.js#31]
Eslint is now at version [2.2.0](https://github.com/eslint/eslint/releases/tag/v2.2.0)

Any reason for not updating to that version of eslint ?

**Comment by Swatinem** [comment]
Look at the PRs, there is #30 already, so it should be ready soon. hopefully :-)

**Comment by netei** [comment]
ok :-)

**Comment by mantoni** [comment]
Yes, I wanted to get the `--fix` and the color fixes out for "old" eslint first. I might find the tine to cut a new major tonight.

If you know of anything that should be considered when moving to eslint 2, please comment here or on the PR.

**Comment by mantoni** [comment]
eslint_d 3.0.0 released with eslint 2.2+. Happy linting!
