### ISSUE TITLE
Running `eslint_d stop` never completes

### ISSUE THREAD

**Issue by abelokon0711** [mantoni/eslint_d.js#312]
Running `eslint_d stop` never completes and I have to cancel it through `Command + C`.

My environment:
eslint_d: 14.0.3
CLI: Git Bash
OS: Windows 10

**Comment by L2jLiga** [comment]
This is due lack of signals support on Windows, I'm currently using `ESLINT_D_PPID` environment variable to auto kill daemon when parent process exited this is also has some drawbacks, however it mostly works fine

In order to provide proper solution launcher and daemon need some rework to provide way for windows users to stop daemon properly

**Comment by L2jLiga** [comment]
Daemon already has http server listening, so may be we can add stop handler here in addition to killing, this way it will be possible to stop daemon on Windows

**Comment by mantoni** [comment]
According to [the docs](https://nodejs.org/api/process.html#signal-events), kill should work on windows.

> Windows does not support signals so has no equivalent to termination by signal, but Node.js offers some emulation with [process.kill()](https://nodejs.org/api/process.html#processkillpid-signal), and [subprocess.kill()](https://nodejs.org/api/child_process.html#subprocesskillsignal):
> 
> Sending SIGINT, SIGTERM, and SIGKILL will cause the unconditional termination of the target process, and afterwards, subprocess will report that the process was terminated by signal.
Sending signal 0 can be used as a platform independent way to test for the existence of a process.

This is exactly what `eslint_d` is doing. So I guess there is something else going on.

**Comment by L2jLiga** [comment]
Indeed, process.kill itself is working, but I was speaking about lack of signals support

I mean that `process.on('SIGTERM', shutdown)` does not work on windows because it terminates unconditionally, so `stopDaemon` hangs forever at `waitForConfig`

**Comment by L2jLiga** [comment]
Sorry if cause misunderstanding

**Comment by abelokon0711** [comment]
I had hoped we could use the Node server for termination listening instead, but unfortunately, it didn't work for me.

**Comment by L2jLiga** [comment]
> I had hoped we could use the Node Net server for termination listening instead, but unfortunately, it didn't work for me.

I've made required changes to work properly on windows: #313
