### ISSUE TITLE
Helix Editor - Eslint fix on save & Prettier config

### ISSUE THREAD

**Issue by Myphz** [mantoni/eslint_d.js#321]
Hello! Thank you for this project. It really speeds up things for me.

I'm using this project with Helix Editor.
Helix editor does not support `codeActionsOnSave` config for now, but it can accept a formatter command, so I created a script to run eslint --fix and prettier format on save, to mimic `codeActionsOnSave` eslint config.

Using regular eslint CLI with stdin option was a pain, because there was no easy way to output the fixed file to stdout (as required by Helix formatter). The format was somewhat inconsistent, I had to format to json and use `jq` to parse it, but if the file didn't have any eslint errors, the eslint CLI used a different JSON structure, making things harder...

It was also quite slow (10+ seconds!).

I edited my formatter script to use eslint_d, and it improves both DX and speed tremendously!

Here is the code for my script (used to be more complex using regular eslint CLI):

eslint-prettier
```bash
#!/bin/bash

# This script was made to be used as a formatter command for the Helix editor.
# This script runs eslint to fix all fixable errors and then runs prettier on the file.
# This script takes the file content from stdin
# and a single argv parameter to be used for the prettier parser.

# This script outputs the content to stdout (as required by helix editor formatter!)
# This script uses eslint_d because somehow it's way faster than regular eslint cli for fixing,
# and provides better DX with --fix-to-stdout CLI option

# If no parser is passed, return error
if [ -z "$1" ]; then
  echo "eslint-prettier: No parser specified for this language!"
  exit 0
fi

input=$(cat -)

eslint_output=$(echo "$input" | eslint_d --stdin --fix-to-stdout)

echo "$eslint_output" | prettier --parser "$1"
```

Helix editor config setup:

languages.toml
```toml
[[language]]
name = "typescript"
language-servers = [
  "typescript-language-server",
  "tailwindcss-ls",
  "eslint",
  "emmet-ls",
  "html-ls"
]
formatter = { command = "eslint-prettier", args = ["typescript"] }
auto-format = true
```

Thank you!

**Comment by mantoni** [comment]
Thank you. I'm not sure: Did you just want to share or is there anything you need from this project?
