### ISSUE TITLE
Is there a way to reuse existing eslint daemon from VSCode ?

### ISSUE THREAD

**Issue by JonathanCabezas** [mantoni/eslint_d.js#335]
I was running `eslint` on my project as a `pre-commit` hook, but recently I added the `typescript-eslint` parser to catch more errors, and the RAM and time usage was multiplied 10x.

I saw people mentionning that VSCode eslint extension uses `eslint_d` under the hood, is there a way to hook into this server ?

Because running `eslint_d` in CLI seems to fire up another eslint server, which makes it even worse than regular `eslint` for my use case.

**Comment by mantoni** [comment]
If VSCode was using `eslint_d` that would be news to me. The editor just has its own in-memory instance of the `ESLint` class per project.

I don't think what you're asking is possible.

**Comment by JonathanCabezas** [comment]
Alright my bad, I guess VSCode live linting is enough and `pre-commit` linting is overkill, I'll remove it.
Thanks for your answer.
