### ISSUE TITLE
running eslint_d from parent directory is slower

### ISSUE THREAD

**Issue by spruce-bruce** [mantoni/eslint_d.js#35]
Hi! I'm a vim user and experience blocking lag with eslint, and still do with eslint_d. I've noticed that my project setup seems to be part of the problem, but since changing my project directory organization isn't an option I'm looking for a solution.

The problem is that I have two javascript projects, an api in node and a react app that consumes that api. So I have a structure like:
```
- project
-- api 
-- frontend
```

I open vim and and run eslint_d from the project directory but there are unique .eslintrc and `node_modules` files in the api/react directories. I'm guessing that eslint_d is having to do some work to reconcile the fact that it's one directory above the node_modules and figure out which eslint bin to use?

**Comment by spruce-bruce** [comment]
Here's some `time` output:

```
aaron@Aarons-MacBook-Pro:~/code/synapse/ims$ eslint_d start
aaron@Aarons-MacBook-Pro:~/code/synapse/ims$ eslint_d status
Running
aaron@Aarons-MacBook-Pro:~/code/synapse/ims$ time eslint_d frontend/application/ui/components/cart/cart.jsx

real	0m0.972s
user	0m0.126s
sys	0m0.018s
aaron@Aarons-MacBook-Pro:~/code/synapse/ims$ time eslint_d frontend/application/ui/components/cart/cart.jsx

real	0m1.209s
user	0m1.112s
sys	0m0.103s
aaron@Aarons-MacBook-Pro:~/code/synapse/ims$ time eslint_d frontend/application/ui/components/cart/cart.jsx

real	0m1.197s
user	0m1.095s
sys	0m0.099s
```

**Comment by spruce-bruce** [comment]
One solution is to open two terminals and have one open to the react app and one to the node app and switch between them when I need to, but I'd prefer not to.

**Comment by mantoni** [comment]
Thanks for the report.

There are three things to consider on the timings you've sent:

- The first invocation is slow because eslint_d loads eslint lazy, so the first call does not have a better performace, only the subsequent calls. The actual eslint performace on a single file is basically those 927 ms minus the eslint_d overhead of about 120 ms.
- The subsequent calls have around 200 ms performance and there shouldn't be a lot of overhead due to your project setup.
- You're using `jsx` files. There is a performance penalty in the underlying JavaScript parser if you enable this.

So my question is, are you sure the performance gets any better with eslint_d if you're invoking it from different current working directories?

If you're on Linux, you may be able to further optimize the performance by using [eslintme](https://www.npmjs.com/package/eslintme).

**Comment by spruce-bruce** [comment]
Sorry, I should have included times in my original issue. Here are times from one directory down linting the same file:

```
$ eslint_d stop
$ eslint_d start
$ eslint_d status
Running
$ time eslint_d application/ui/components/cart/cart.jsx

real	0m6.188s
user	0m0.125s
sys	0m0.018s
$ time eslint_d application/ui/components/cart/cart.jsx

real	0m0.268s
user	0m0.123s
sys	0m0.019s
$ time eslint_d application/ui/components/cart/cart.jsx

real	0m0.246s
user	0m0.122s
sys	0m0.018s
$ time eslint_d application/ui/components/cart/cart.jsx

real	0m0.267s
user	0m0.121s
sys	0m0.018s
```

As expected, the first call is slower, but here the times are improved over running one directory up. I'm not sure if these times are indicative of an actual problem or not, but there is definitely a noticeable difference in speed of linting a single jsx file based on the cwd. I'm wondering if this is because of my eslint plugins?

```
    "eslint-plugin-babel": "^3.1.0",
    "eslint-plugin-react": "^3.16.1",
```

I'm running OS X - might try to get eslintme working anyway, though, thanks for the suggestion! Also, thanks for the package! I understand how hard it is to make time for stuff like this, it's appreciated!

**Comment by mantoni** [comment]
Oups. Sorry, I also didn't read your numbers carefully. I didn't see there is a "1" before the dot :see_no_evil:. There's clearly something wrong with that.

**Comment by spruce-bruce** [comment]
No worries! I'll see if I can get some time to come up with a repeatable case for you (I'm pretty swamped at the moment, but there's always hope)

**Comment by mantoni** [comment]
Please report back if you have more insights to share. I'm happy to reopen if this is still an issue. Closing for now.
