### ISSUE TITLE
Exit code is always 0

### ISSUE THREAD

**Issue by fatso83** [mantoni/eslint_d.js#37]
Currently `eslint_d` cannot be used as a drop-in replacement for `eslint` because the return status is always 0 :cry:

**Comment by mantoni** [comment]
Maybe you're on an outdated version? The latest release should have fixed that: https://github.com/mantoni/eslint_d.js/commit/8eb60254e906f6ee8fda2365cfa9476eb8d35199

**Comment by mantoni** [comment]
If this is still an issue, let me know and I’ll re-open.
