### ISSUE TITLE
Output format

### ISSUE THREAD

**Issue by eliseumds** [mantoni/eslint_d.js#4]
First of all, this project is really usually to me, so, thanks! I've been testing it and faced the following issues:

* Couldn't get it to work by installing the modules locally (in the root of my project), only globally
* Had to add *--format compact* to the command line options, otherwise it wouldn't highlight the problematic chunks

If it's a misconfiguration from my side, sorry.

**Comment by mantoni** [comment]
Yes, the initial version (1.0.0) always used `--format compact` internally, but I've now added all the eslint options and wanted to align the defaults. Therefore the format has to be configured for your editor now. I have updated the vim docs and this is in the works for Sublime: https://github.com/roadhump/SublimeLinter-eslint/pull/86

Your other point is no so easy to address. It's currently only working as a global install.

**Comment by mantoni** [comment]
@eliseumds Is this still an issue or can we close?

**Comment by eliseumds** [comment]
@mantoni you may close it, ty.
