### ISSUE TITLE
eslint_d does not seem to support "no-prototype-builtins" even though it is included in eslint

### ISSUE THREAD

**Issue by blacksun1** [mantoni/eslint_d.js#42]
Hello,

I am seeing a strange problem in eslint_d v3.1.0. It does not seem to include the rule "no-prototype-builtins" which is included in the same version of eslint (v2.11.1, http://eslint.org/docs/rules/no-prototype-builtins)

Please note I also tried to include debug information for you (`eslint_d --debug index.js`) but the --debug command line argument does not seem to do anything.

**Environment**

``` bash
> node --version
v4.4.4

> npm --version
3.9.5

> eslint_d --version
v2.11.1 (eslint_d v3.1.0)
```

**Configuration**

```
module.exports = {
  "extends": "eslint:recommended",
  "env": {
    "es6": true
  },
  "rules": {
    // Disallow use of Object.prototypes builtins directly
    "no-prototype-builtins": [
      "error"
    ]
  }
};
```

**Error**

```
> eslint_d index.js

/Users/bruces/Projects/eslint-config-blacksun1/index.js
  1:1  error  Definition for rule 'no-prototype-builtins' was not found  no-prototype-builtins

✖ 1 problem (1 error, 0 warnings)
```

I was able to see this error in Sublime text using the Sublime Linter plugin and from the command line.

Thanks in advance,

**Comment by blacksun1** [comment]
I think that the problem with the --debug command line option is here

https://github.com/mantoni/eslint_d.js/blob/master/lib/linter.js#L58 

```js
  var engine = new cwdDeps.eslint.CLIEngine(
    translateOptions(currentOptions, cwd)
  );
```

`TranslateOptions` does not return a debug option so it will never return it and therefore never send to the `CLIEngine`.

**Comment by blacksun1** [comment]
Umm, maybe not. Looks like eslint handles the debug flag in a non-standard way. I will continue looking.

**Comment by mantoni** [comment]
Hm, are you sure eslint_d isn't using a project local installed eslint that is < 2.11 and doesn't have the feature yet? There are two ways eslint will be loaded by `eslint_d`: From `node_modules/eslint` in the current directory, or eslint_d's own dependency as a fallback.

Also, if you updated eslint recently, make sure to run `eslint_d stop` to make sure you're not working with another eslint version from eslint_d's in-memory cache.

**Comment by mantoni** [comment]
Please report back if you have more insights to share. I'm happy to reopen if this is still an issue. Closing for now.
