### ISSUE TITLE
Update version to eslint 3

### ISSUE THREAD

**Issue by fab1an** [mantoni/eslint_d.js#44]
Thank you.

**Comment by mantoni** [comment]
Released `v4.0.0` which now comes with eslint 3. If you have a project local eslint installation, then that version is used. The version coming with `eslint_d` is used as a fallback.

Please make sure to run `eslint_d stop` when you upgrade.

**Comment by fab1an** [comment]
Awesome. Was that the case with eslint-3 too, because I had a local eslint-3 installation and it still used it's own eslint-2.

**Comment by mantoni** [comment]
It should have used the local install if you restarted the eslint_d server.

**Comment by fab1an** [comment]
I "restarted" by killing the node process.
