### ISSUE TITLE
Security: Listen only on localhost OR use file based sockets

### ISSUE THREAD

**Issue by moll** [mantoni/eslint_d.js#45]
Hey,

An otherwise very useful daemon, but please, ASAP, stop listening on 0.0.0.0 or, better yet, listen through a file based socket that is only accessible to the current user!

**Comment by moll** [comment]
Actually, unless there's going to be CSRF protection, I'd forgo an IP socket immediately and go with a file based one. With a bit of creativity, I'm sure any random webpage on the net can cause this thing to be invoked.

**Comment by mantoni** [comment]
Thanks. I would have preferred a file based socket, but windows is still around. I’m letting the OS assign the port which should make it a little harder. But you’re right, I will change to listening on `127.0.0.1` explicitly. Would that we good enough?

**Comment by moll** [comment]
I don't know how to solve this for Windows without a CSRF token of some sort, but for other platforms this _should_, or dare I say must, resort to file based sockets for now. Fundamentally it's the same security vulnerability as any other CSRF and sadly not solved by listening on localhost.

**Comment by moll** [comment]
To add, this vulnerability is unfortunately fairly common: https://blog.jetbrains.com/blog/2016/05/11/security-update-for-intellij-based-ides-v2016-1-and-older-versions/

**Comment by mantoni** [comment]
Hm, yeah. How about generating a uuid at server startup and store it along with the port number in the ~/.eslint_d.json? The uuid can act as a token that is sent with each request and has to match what the server expects. Shouldn't be hard to do, but would be very effective. An attacker would need file system access in which case there is nothing to protect anymore...

**Comment by moll** [comment]
Yeah, that'd work nicely. You could store that in the same file as the port and randomize it on start.

**Comment by mantoni** [comment]
Released v4.0.1 and v3.1.2 with a fix. Thanks again for reporting.

**Comment by moll** [comment]
👍
