### ISSUE TITLE
Improve READEME

### ISSUE THREAD

**Issue by PombaM** [mantoni/eslint_d.js#49]
Hey man, thanks for making sublime linting great again! Your eslint_d.js is a joy to use.

However while testing, i was playing with [moar speed](https://github.com/mantoni/eslint_d.js#moar-speed), it works and it's great but I get a performance hit when i use that option.

Since i have no clue how to use `nc`, i can't revert back to previous state. Can you please update your [README](https://github.com/mantoni/eslint_d.js/blob/master/README.md) detailing how to revert back . Thanks anyways!

Screenshots:
![screenshot from 2016-09-28 14-09-31](https://cloud.githubusercontent.com/assets/11157420/18905997/6977b8e6-8585-11e6-809b-31cf41ae20f8.png)

In the screenshot, it shows 1.3GB RAM consumption but i have seen it's memory consumption way above.

**Comment by mantoni** [comment]
Hm. Maybe some socket leak. I will see what I can find. How sid you integrate that with Sublime?

As a temporary workaround you can simply `eslint_d restart`. That should bring the memory down again, unless the leak happens on the sublime side.

**Comment by PombaM** [comment]
> How did you integrate that with Sublime

Not sure what you mean :smile:  but all i did was follow your README instructions. 

Somethings to be noted though:

- I am running Ubuntu 16.04 LTS
- I am using Sublime Text 3
- Running it for 9-10+ hours

Let me know if you need any additional info.

**Comment by mantoni** [comment]
Hm. Maybe @roadhump or @doctyper can help with this?

**Comment by mantoni** [comment]
@PombaM Any new on this? Is this still an issue?

**Comment by PombaM** [comment]
Hey @mantoni, I have upgraded my device (Dell XPS 13 9350) and I haven't seen that issue yet. Thanks.

**Comment by mantoni** [comment]
Thanks for the update. Will close for now. Please let me know if it shows up again and I'll re-open the issue.
