### ISSUE TITLE
Support for Atom

### ISSUE THREAD

**Issue by numaanashraf** [mantoni/eslint_d.js#5]
Any plans to extend support to [Atom](https://atom.io/)? I'm currently liniting on save via [linter](https://atom.io/packages/linter) & [linter-eslint](https://atom.io/packages/linter-eslint).

**Comment by mantoni** [comment]
Sure. Since version 2.1.0 eslint_d can be used as a drop-in replacement except for linting stdin. Would that be required for Atom?

Otherwise, open an issue with `linter-eslint` to support eslint_d as an alternative executable.

**Comment by mantoni** [comment]
[As suggested by the Atom eslint project](https://github.com/AtomLinter/linter-eslint/issues/215), there is no performance gain to expect from using `eslint_d`. I have added a note to the readme accordingly.

**Comment by numaanashraf** [comment]
Ah! Thanks @mantoni.
