### ISSUE TITLE
Support --print-config

### ISSUE THREAD

**Issue by aaronjensen** [mantoni/eslint_d.js#50]
flycheck-eslint now uses `--print-config` to verify that a file has a config. This doesn't work in `eslint_d`, effectively disabling it.

**Comment by mantoni** [comment]
Thanks. Passing parameters through to eslint is pretty simple. Care to take a stab at it yourself?

**Comment by aaronjensen** [comment]
@mantoni I tried adding it to options and setting it in the options object but it still ran the linting, so I'm not sure what to try next. I didn't dig too deep though, is there something obvious I'm missing?

**Comment by mantoni** [comment]
The important thing is to run `eslint_d restart`. Otherwise your changes aren't picked up.
