### ISSUE TITLE
Support --fix to stdout?

### ISSUE THREAD

**Issue by aaronjensen** [mantoni/eslint_d.js#52]
At the moment, `--fix` writes to the file. This makes it difficult to add as a pre-save hook in editors. There is no official support for writing the fixed output to stdout via the cli (see https://github.com/eslint/eslint/issues/6612) but it can be done w/ the api.

It'd be great to have `eslint_d` support that for the added speed boost, but it'd be a non-standard flag. Would you be up for having that in `eslint_d`?

**Comment by mantoni** [comment]
If this feature is an official part of the API, then why not. What would this look like? `--fix --stdout`?

**Comment by mrapogee** [comment]
I imagine it would be more like `--fix-to-stdout` since `--stdout` wouldn't make sense without `--fix`

Example Usage: `echo "var t= 5" | eslint_d --stdin --fix-to-stdout`
stdout: `var t = 5;`

**Comment by mantoni** [comment]
Makes sense. `--fix-to-stdout` then 👍 

Was thinking about this feature a bit, and this will be awesome in vim for things like "fix on `:w`" or just within the open buffer. Really cool idea @aaronjensen.

**Comment by aaronjensen** [comment]
This sounds good to me. @mrapogee has a gist on how he did this on its own if it's any help to the implementation: https://gist.github.com/mrapogee/4c64a5c85064f9d907d8c9a5b4c8b045

**Comment by mantoni** [comment]
Cool! I will not have time to add this myself as I'm traveling the next couple of days. If one of you can make a PR, I will merge and cut a release. It would be brilliant if you could also include instructions on how to make this work in emacs / vim / sublime ... whatever editor you know best.
