### ISSUE TITLE
Move lengthy auto-fixing setup for Emacs out of README

### ISSUE THREAD

**Issue by mantoni** [mantoni/eslint_d.js#56]
I think the [emacs section about auto-fixing](https://github.com/mantoni/eslint_d.js#automatic-fixing) grabs too much land in the README. I would like that to live elsewhere and be cross-linked into the README to have this as one or two line bullet point.

@aaronjensen You mentioned you would like to move this into a separate project, but we can also just enable the Wiki for this project. Alternatively, it could be a snippet that lives in a separate file in this repository if we find a good place for it. What do you think?

**Comment by aaronjensen** [comment]
I'm quite good w/ either of those latter options. I won't have time to do the separate project just yet. A wiki would be nice because then I could keep it up to date.

**Comment by mantoni** [comment]
Cool. I've enabled the wiki.

**Comment by mantoni** [comment]
This has been done. The auto-fixing setup can now be found at https://github.com/aaronjensen/eslintd-fix.
