### ISSUE TITLE
Fallback to global eslint

### ISSUE THREAD

**Issue by silverwind** [mantoni/eslint_d.js#58]
Right now the order to find eslint is
1. local node_modules
2. bundled version

I prefer to use a global eslint installation to save space and avoid updating micromanagement. Would it be possible to have a loading order like this?
1. local node_modules
2. global node_modules
3. bundled version

**Comment by mantoni** [comment]
I would support this, but it's not trivial to do. `eslint_d` needs access to the API of the module, not just the binary from the `PATH`. So there would have to be some magic to resolve the API of the globally installed module. Do you know a reliable way to do this?

**Comment by silverwind** [comment]
The [requireg](https://github.com/h2non/requireg) module looks to be useful for this purpose. A quick test:

##### eslint installed global only
```
> require("requireg").resolve("eslint")
'/Users/silverwind/.npm-global/lib/node_modules/eslint/lib/api.js'
```

##### eslint installed local and global
```
> require("requireg").resolve("eslint")
'/Users/silverwind/git/test/node_modules/eslint/lib/api.js'
```

It likely doesn't support [yarn](https://github.com/yarnpkg/yarn) when it uses a different prefix than npm, but that's acceptable I think.

**Comment by mantoni** [comment]
Glanced over `requireg` and it seems nice. I don't have free capacity to add this feature for at least the next two weeks. If you have some time to make a PR, I'll happily merge and cut a release.

**Comment by silverwind** [comment]
Okay, I will do a PR soon.

**Comment by silverwind** [comment]
Turns out this is a bit more complex than I thought because `requireg` will prefer the packaged eslint. I will try to come up with a module that resolves to global modules only, supporting both yarn and npm.

**Comment by mantoni** [comment]
Huh, wow! Shame it doesn't fit out of the box. Thanks for looking into it.

**Comment by silverwind** [comment]
Module is up: https://github.com/silverwind/globalrequire

Still got to test it on Window.

**Comment by mantoni** [comment]
If you're using `exec` anyway, you can call `npm root -g` to get the path. Less parsing. However, isn't that quite slow? We would add two attempts to run external processes before using the fallback.

**Comment by silverwind** [comment]
Thanks for `npm root -g`, I'll do that for now.

And yes, I'd like to avoid the `exec` too. I think I can safely drop the exec for `yarn` as the module path is pretty easy to build yourself. I think I'll dig into npm source to find out how they build it and just replicate that, like I did for yarn.

**Comment by silverwind** [comment]
Okay, I went ahead and did the same thing as `requireg` did: Load npm's config and get the prefix from there, so no more `exec` necessary.

**Comment by mantoni** [comment]
Looks good. When using this, how do plugins behave? Can they still work or can they even be installed globally as well?

**Comment by silverwind** [comment]
Good question, I need to put together a PR to know if global plugins will be found correctly. I'm pretty sure the will as the `eslint` CLI is already able to find global plugins.

**Comment by dfournier** [comment]
I also have a similar request. Do you think it would be possible to install `eslint_d` globally but user a local `eslint`?

**Comment by mantoni** [comment]
@dfournier That is the default behavior already. It's actually how `eslint_d` is supposed to be used. I also have one global instance of `eslint_d` myself and it picks up the project-local `eslint` install and config. This issue is about the fallback behavior in case no local `eslint` is found.

**Comment by dfournier** [comment]
Is there something wrong on my computer?

```bash
npm install -g eslint_d
npm install -SE eslint@3.18.0

eslint_d --version
v3.19.0 (eslint_d v4.2.5)

node_modules/.bin/eslint --version
v3.18.0

node -v
v5.3.0

npm -v
3.8.8
```

I can open another issue if you prefer :)

**Comment by mantoni** [comment]
Please open a new issue. From the version numbers you're posting here, everything seems fine. The one thing you should always try though, is to run `eslint_d stop` and then testing again. You might have an outdated cached version in use.

**Comment by silverwind** [comment]
Maybe something worth to look at for importing global modules:

https://github.com/sindresorhus/import-global

Note that I'm personally no longer interested in using global eslint as I've switched over to using local eslint only, but others might still find it valuable.

**Comment by mantoni** [comment]
@silverwind Thanks for the pointer 👍
