### ISSUE TITLE
Eslint_d tries to lint config file

### ISSUE THREAD

**Issue by roadhump** [mantoni/eslint_d.js#6]
It looks like bug with options

```
eslint_d src/1.js --config ./.eslintrc

... // some errors
/Users/roadhump/Projects/xx/src/1.js: line 5, col 1, Error - Multiple blank lines not allowed. (no-multiple-empty-lines)
/Users/roadhump/Projects/xx/.eslintrc: line 2, col 13, Error - Line X: Unexpected token

7 problems
```

**Comment by mantoni** [comment]
Interestingly, I can't reproduce. I noticed that I had a slightly newer version of `optionator` in use than `eslint` so I downgraded in v2.1.0. Did you try to install freshly?

**Comment by mantoni** [comment]
Also, I'm on Node 4.0 with npm@3. What's your setup?

**Comment by roadhump** [comment]
This is eslint_d v2.1.0 and I use Node 4.0 and npm 2

**Comment by mantoni** [comment]
Can you provide the `.eslintrc` file?

**Comment by mantoni** [comment]
Can you try again with the latest patch, it might fix this too.

**Comment by roadhump** [comment]
@mantoni Yes, it seems ok now
