### ISSUE TITLE
Support for prettier

### ISSUE THREAD

**Issue by aaronjensen** [mantoni/eslint_d.js#62]
Hey @mantoni I've recently started trying out [`prettier`](https://github.com/jlongster/prettier) along with [`prettier-eslint`](https://www.npmjs.com/package/prettier-eslint). It'd be great to somehow be able to have eslint_d run code through prettier before passing it to fix.

I could build it in as an explicit feature (is it weird to couple eslint_d to a completely different tool?) or I could make some sort of prefilter plugin interface... Ideally I could use something like [`eslint-plugin-prettier`](https://github.com/not-an-aardvark/eslint-plugin-prettier) but I have rules that disagree w/ prettier, so it won't work int hat way.

Thoughts?

**Comment by mantoni** [comment]
I don't think this belongs in eslint_d. An important part of eslint_d is to stay small to ensure startup is fast. Instead, we could expose an API for eslint_d that allows you to build a new, specialized tool on top of it. Do you think that would work?

**Comment by aaronjensen** [comment]
Yeah that would probably work, though I'm having a hard time picturing what would be exposed at the moment

**Comment by josephfrazier** [comment]
I've just started working on an eslint_d fork that uses prettier instead. It's still a work-in-progress, but I've published a functional version already: https://github.com/josephfrazier/prettier_d.js

**Comment by mantoni** [comment]
Awesome! It's nice to see the concept being transferred. :+1:
