### ISSUE TITLE
autofix config in vim

### ISSUE THREAD

**Issue by hafeyang** [mantoni/eslint_d.js#64]
here is my vimrc file ,i wanna to autofix eslint file
```
" settings for Syntastic
set statusline+=%#warningmsg#
set statusline+=%{SyntasticStatuslineFlag()}
set statusline+=%*
let g:syntastic_always_populate_loc_list = 0
let g:syntastic_auto_loc_list = 0
let g:syntastic_check_on_open = 1
let g:syntastic_check_on_wq = 0
let g:syntastic_check_on_w = 1
let g:syntastic_javascript_checkers = ['eslint']
let g:syntastic_javascript_eslint_exec = 'eslint_d'
"let g:syntastic_javascript_eslint_args = '--fix-to-stdout' 
```
`g:syntastic_javascript_eslint_args` `g:syntastic_javascript_eslint_tail` seems not work

**Comment by aaronjensen** [comment]
I don't think you would use syntactic for that. Syntactic is just for pointing out errors, not replacing text as far as I know. 

Take a look at the instructions on prettier r for some examples of how they do it. https://github.com/prettier/prettier/blob/master/README.md#vim

If you get something working maybe you could contribute the instructions back? Thanks!

**Comment by mantoni** [comment]
I just added an example to the readme: https://github.com/mantoni/eslint_d.js#automatic-fixing

This allows you to fix the current selection in-place or the entire buffer.

**Comment by aaronjensen** [comment]
Nice. That doesn't cover fix on save, but the instructions at prettier can be adapted. I bet it wouldn't be hard to add eslint_d to https://github.com/sbdchd/neoformat as well.

**Comment by Daghall** [comment]
This worked for me:
```
" Autofix on write
autocmd BufWritePre *.js execute "normal mF" | silent execute "%!eslint_d --stdin --fix-to-stdout" | execute "normal `F"
```
