### ISSUE TITLE
Parsing error: ecmaVersion must be 3, 5, 6, or 7

### ISSUE THREAD

**Issue by acarl005** [mantoni/eslint_d.js#69]
I have the following options in my `.eslintrc`

```js
{
  "parserOptions": {
    "ecmaVersion": 2016
  }
}
```

This is valid when I use the `eslint` command directly. My `eslint --version` is `v3.19.0`. It is correctly linting my files.

However, when I use `eslint_d` instead, I get this error instead:

```
/Users/andy/Desktop/ipmask.js
  0:0  error  Parsing error: ecmaVersion must be 3, 5, 6, or 7

✖ 1 problem (1 error, 0 warnings)
```

The `eslint_d --version` says `v3.19.0 (eslint_d v4.2.5)`. So the eslint version is the same but parsing fails when it should be valid. I tried reinstalling `eslint_d` and I ran `eslint_d restart` but no luck.

**Comment by mantoni** [comment]
Weird. `eslint_d` doesn't parse that file itself. Do you have a different eslint version in your `node_modules`?

**Comment by acarl005** [comment]
It turns out I had a `node_modules` directory loitering in my home directory. Removing that solved the problem. Thanks!
