### ISSUE TITLE
output is missing colors

### ISSUE THREAD

**Issue by raine** [mantoni/eslint_d.js#7]
Perhaps intentionally?

<img width="1280" alt="screen shot 2015-09-24 at 0 02 39" src="https://cloud.githubusercontent.com/assets/11027/10058709/974f0a4e-624f-11e5-8d53-372dcd70858d.png">

**Comment by mantoni** [comment]
No, not intentionally. I've seen this as well and my guess is that there is a detection in eslint whether it's running in a tty. I didn't investigate how to work around it yet.

**Comment by mantoni** [comment]
Fix released in `2.5.0`.

**Comment by mantoni** [comment]
Another fix release in `2.5.1`. Colors where only working for global eslint, now it should also work for project local eslint.
