### ISSUE TITLE
--stdin using netcat

### ISSUE THREAD

**Issue by calebeby** [mantoni/eslint_d.js#73]
Hello,

I would like to use `nc` to pass stdin into `eslint_d`. Is this possible?

I tried using
```
cat file.js | cat <(echo "$TOKEN $PWD --stdin") - | nc -q 0 localhost $PORT
```
 as seen [here](https://github.com/josephfrazier/prettier_d#moar-speed), but it only prints
```
RangeError: "size" argument must not be larger than 2147483647
# exit 1
```

Thanks

**Comment by mantoni** [comment]
You're referring to the `prettier_d` project documentation. Try the way that is documented in this project:

```bash
echo "$TOKEN $PWD file.js" | nc localhost $PORT
```

**Comment by mantoni** [comment]
Oh, sorry, I now realized that you request is regarding the combination of netcat and the `--stdin` behavior. That is currently not supported. There is a [JSON protocol between the client and the server](https://github.com/mantoni/eslint_d.js/blob/0e950ade29a562f3c1dc79d6ea5c41d791394f84/lib/client.js#L72) that is used for this purpose.

The documented text based protocol has currently no implementation for passing through the file contents. If you'd want to give it a shot, I'd be happy to assist and merge a pull request.
