### ISSUE TITLE
Change config node_modules to current project

### ISSUE THREAD

**Issue by zhouytforever** [mantoni/eslint_d.js#76]
While I'm trying
```
" Autofix entire buffer with eslint_d:
nnoremap <leader><leader>f mF:%!eslint_d --stdin --fix-to-stdout<CR>`F
" Autofix visual selection with eslint_d:
vnoremap <leader><leader>f :!eslint_d --stdin --fix-to-stdout<CR>gv
```
I got the errors of some modules or plugins can't find
"Error: Failed to load plugin react: Cannot find module 'eslint-plugin-react' ”

So I know it means I need change the config to locale instead of global

But I don't know how

Here is my eslintrc.json :
```
{
    "extends": "airbnb"
}
```

**Comment by mantoni** [comment]
Does `eslint_d .` work as expected for that project?

**Comment by zhouytforever** [comment]
No
Can't it recognize my package.json ?

**Comment by mantoni** [comment]
Does `eslint .` even work? Because `eslint_d` shoukd behave exactly the same.

**Comment by zhouytforever** [comment]
the same problem

**Comment by zhouytforever** [comment]
So ... should I change the work dir to my project as the title saying?
Then how

**Comment by mantoni** [comment]
If `eslint` does not work, you're not having an `eslint_d` problem. Helping with eslint configuration issues is out of scope for this project. Please try posting on StackOverflow or other eslint specific help channels. If it works with eslint as expected but doesn't with eslint_d, open a new issue and I'm happy to help.
