### ISSUE TITLE
How to use local eslint

### ISSUE THREAD

**Issue by zhouytforever** [mantoni/eslint_d.js#77]
I just want to use eslint_d like   "./node_modules/.bin/eslint . --ext .vue"
Can you tell me how ?

**Comment by mantoni** [comment]
I think I don't understand the question. You can run eslint_d like `./node_modules/.bin/eslint_d . --ext .vue`, or you can install it globally (`npm install -g eslint_d`) and then run `eslint_d . --ext .vue`.

What is it that you're trying to do and it doesn't work?

**Comment by zhouytforever** [comment]
In vim, I can only use the global eslint_d. What I want is every node_modules is not global except the eslint_d.   So I can use the global eslint_d and the project's modules and rules . So that I can keep the rules with my teemates like vs_code does.

**Comment by mantoni** [comment]
The behavior you’re asking for is the default. While `eslint_d` is used globally, it will load the `eslint` instance in the current directory with the local rules. This means that a cached instance of each project directory will live in the internal cache of `eslint_d`.

If something doesn’t work as expected, you might have changed the eslint install or the configs after invoking `eslint_d`. These changes are not picked up automatically. Please run `eslint_d stop` to stop the server and discard the cache, then try to lint again.

**Comment by mantoni** [comment]
I guess silence means I answered the question. Closing.
