### ISSUE TITLE
Support `--fix-dry-run`

### ISSUE THREAD

**Issue by w0rp** [mantoni/eslint_d.js#78]
ESLint now offers a `--fix-dry-run` option. I think it would be a good idea to alias `--fix-dry-run` to the existing `--fix-to-stdout` option in `eslint_d`. Then it will be easier to swap out ESLint commands with `eslint_d` for use in various editor plugins.

**Comment by aaronjensen** [comment]
As far as I can tell, `--fix-dry-run` doesn't actually output anything, so it's not the same thing. Am I missing something?

**Comment by aaronjensen** [comment]
Ah, need to pass `--format=json`. Supporting `--fix-dry-run` would be fine, but it's a very different flag, so it should not be an alias.

**Comment by w0rp** [comment]
The usage is the same. You use `eslint --stdin-filename path/to/file.js --stdin --fix-dry-run`, and you get the fixed version of the file via stdout.

**Comment by w0rp** [comment]
Hmm, it does seem like you need a `--format` for it. It seems like a pointless option to me, then. The only use for such an option is to get the fixed file via stdout.

**Comment by aaronjensen** [comment]
Right, the idea would be that the editor would use the json output, but there are already plugins out there (like `eslintd-fix` for Emacs) that rely on the existing `--fix-to-stdout` behavior.

**Comment by w0rp** [comment]
It might be worth supporting the new option as defined in ESLint, and keeping the existing option.

**Comment by aaronjensen** [comment]
Agreed. Would you like to submit a PR for that?

**Comment by w0rp** [comment]
I might give it a go at some point.

**Comment by Mar-Ser** [comment]
@mantoni I think now this issue can be closed.
