### ISSUE TITLE
Hanging in windows

### ISSUE THREAD

**Issue by tivac** [mantoni/eslint_d.js#8]
I'm running `eslint_d@2.1.0` on `node@4.1.0` with `npm@3.3.0` on a Win7x64 box.

`eslint_d test.js` just hangs forever, as does any other `eslint_d` command. Am I misunderstanding how to use this?

I don't see it creating a ` ~/.eslint_d_port` file, so I suspect something is failing somewhere and just never outputting.

**Comment by mantoni** [comment]
Thanks for reporting. I'll see if I can reproduce on a windows machine at work tomorrow.

**Comment by mantoni** [comment]
I tried in `cygwin` and that works fine. I have trouble getting node to run in a standard shell due to my weird setup here. If anyone could help reproduce the issue, that would be very welcome.

**Comment by tivac** [comment]
I'm launching from a `cmd` shell. I was also able to repro at home running `node@4.1.1` on Win10x64.

**Comment by mantoni** [comment]
I managed to reproduce now and provided a fix in `v2.1.1`.
