### ISSUE TITLE
Does this only work on Cloud 9 created instances?

### ISSUE THREAD

**Issue by marcato15** [mantoni/eslint_d.js#82]
I tried using this with a SSH Box (pretty plain Ubuntu 16.04 setup) but it doesn't seem to be triggering. Is there anything special about getting it working on something other than the default Cloud 9 EC2 instance?

**Comment by mantoni** [comment]
It should work wherever eslint is working. Can you elaborate what exactly is happening, which node version you’re using and what `eslint_d -v` prints?

**Comment by marcato15** [comment]
I'm sorry. I was using a package dependent on `eslint_d` and accidentally wound up clicking on the wrong issues page. I don't think the issue I'm having has anything to do with `eslint_d`.
