### ISSUE TITLE
Support IPv6 Connections

### ISSUE THREAD

**Issue by webnard** [mantoni/eslint_d.js#83]
My machine was, by default, attempting to connect to eslint_d over IPv6 before trying IPv4, which caused a considerable slowdown. It'd be nice if this ran, by default, on both 127.0.0.1 and ::1

**Comment by mantoni** [comment]
Makes sense. Would you care to send a pull request for this?

**Comment by webnard** [comment]
Sure! Can't take care of it right now, but in a few hours or sometime tomorrow I can submit something.

**Comment by mantoni** [comment]
I guess #84 is somewhat related.

**Comment by webnard** [comment]
Yeah, I imagine #84 would have fixed it. Sorry for the absence of a promised PR. I changed my hosts file, and this was no longer a thorn in my side, so I kind of forgot about it. :)

**Comment by mantoni** [comment]
Shall we close this then?

**Comment by webnard** [comment]
Sounds good to me.
