### ISSUE TITLE
Detect other "Engines"?

### ISSUE THREAD

**Issue by laduke** [mantoni/eslint_d.js#85]
Hi! Love this thing. 
So, I've been running into lots of projects that use [standard](https://github.com/standard/standard), which means there's no eslint config files in the project, which means eslint_d doesn't know what rules to use.  ( you run the linter with `standard foo.js` instead of `eslint foo.js` )

I was bugging the nice people at eslintd-fix about it and trying to figure out how to get emacs to use the right linter, but then I got to thinking, maybe here would be a better place to address? 

Curious what you'all think about detecting `standard` in package.json or node_modules, and spinning that up instead of eslint? I guess it's awkward to special-case stuff in like this, but on the other hand, standard is so widely used.

**Comment by mantoni** [comment]
Hi, thanks for writing. I thought about support for standard a while back. Since standard is based on eslint, it should be possible, but from my brief looking around, it needs a bit of work in eslint_d to adapt.

If you want to look into it, I‘d be happy to assist :)

**Comment by laduke** [comment]
Cool! thanks. 

Silly question, how do you usually run eslint_d from inside this repo, for dev purposes? 
If I do like 

`~/s/eslint_d.js ❯❯❯ ./bin/eslint_d.js lib/linter.js      `                                                                                                                  

I get 

`TypeError: cwdDeps.eslint.CLIEngine is not a constructor`

same thing if I npm link it 🤔

**Comment by laduke** [comment]
Thanks! gonna look into.

**Comment by laduke** [comment]
Haha, pretty tricky.

**Comment by tribou** [comment]
@mantoni I also love this thing and am wondering about "engine" support... 

Scenario 1: AST Daemon
For instance, let's say I want to augment my IDE (such as vim) with an API that accepts a JS file and returns a list of all the function names used in the file (could be piped to FZF/etc). My first thought was to translate the file into the AST (via Esprima/Espree/Babel-parser/etc)...but I'd want to use the `eslint_d` core features to avoid the Node startup time.

Scenario 2: Prettier Daemon
Looks like this project started on this idea: https://github.com/rstacruz/prettier-eslint_d But it warns "EXPERIMENTAL" which wards off all but the bravest of souls.

Scenario 3: StandardJS
[As mentioned by OP](https://github.com/mantoni/eslint_d.js/issues/85#issue-304514252)

Perhaps the caching + daemon capabilities of this awesome `eslint_d` package could be encapsulated, and a plugin API could be exposed/documented?

Prior art:

- [VSCode's JSON RPC](https://www.npmjs.com/package/vscode-jsonrpc) 
- [Prettier's JSON-RPC discussion](https://github.com/prettier/prettier/issues/730)
- [ESLint's JSON-RPC discussion](https://github.com/eslint/eslint/issues/8109)

**Comment by mantoni** [comment]
Thanks for posting. I had exactly the same thoughts for quite a while and already refactored the code with this goal in mind. Therfore it was quite easy for me to extract a library that allows you to build your own Prettier or Standard daemons.

I called it `core_d` and here it is, including docs: https://github.com/mantoni/core_d.js

Version `1.0.0` has just been released on npm and it's used by `eslint_d` in `v7.3.0` already.

Please let me know what you think. Happy coding!

**Comment by tribou** [comment]
Fantastic! I'll try it out and report any results over there soon 👏
