### ISSUE TITLE
--no-color argument does not apply to all output

### ISSUE THREAD

**Issue by orzechowskid** [mantoni/eslint_d.js#90]
with eslint_d 6.0.1 and eslint 5.3.0, the `--no-color` flag appears to affect the strings which eslint_d outputs but not the strings that eslint itself outputs.  It looks like that command-line argument is not being passed through to eslint.

![screenshot from 2018-08-17 18-00-23](https://user-images.githubusercontent.com/2667110/44290600-7985f500-a247-11e8-9fdd-434a9fc28d8d.png)

notice the file still has syntax highlighting applied to it (which in my case is causing escape codes to be printed in the output window of my IDE).

I wonder if this was exposed after #88 got fixed?

**Comment by mantoni** [comment]
Hey, thanks for reporting. I'm trying to reproduce the issue, but apparently I'm missing some details. I get close to the output in your screenshot by enabling the codeframe formatter with `--format codeframe`. However, it doesn't do the syntax highlighting in my case, regardless of color options.

<img width="591" alt="bildschirmfoto 2018-08-18 um 21 34 18" src="https://user-images.githubusercontent.com/332271/44302689-8b8e9300-a32e-11e8-8de4-9c03470ef786.png">

How did you configure eslint?

**Comment by orzechowskid** [comment]
aha, I don't have any formatter specified in my .eslintrc.js file but I do have `parser: 'babel-eslint'` which proved to be the source of my problems.  Setting it to 'esprima' seemed to take care of my issues.  

Sorry for the false alarm, and feel free to close.

**Comment by mantoni** [comment]
Thanks for the update. It seems weird that the parser changes the formatter output though 🤔
