### ISSUE TITLE
Include `eslint` and usable versions as a peer dependency

### ISSUE THREAD

**Issue by sharmilajesupaul** [mantoni/eslint_d.js#98]
This is definitely not urgent, but I'm noticing that for apps using an older version `eslint`, we end up with two versions of `eslint` in `node_modules` because this package explicitly depends on `eslint@^5.4.0`. 

It would be great if this package allowed a range of eslint versions that are supported. Similar to this: https://github.com/benmosher/eslint-plugin-import/blob/b4a2f11fcacc6b2f048da4b29cfc896e682f17d1/package.json#L72L74

This would give us more flexibility around which version of `eslint` to use at the top level and we would be able to dedupe that against the dependencies in this package.

Happy to submit a PR if you're busy!

**Comment by mantoni** [comment]
Hm. So you’re using `eslint_d` as a dependency of a module? Can you explain why that is favorable over a global install?

The reason for making eslint a dependency is to provide a default in case it’s not available in the current working directory. It should still be desuped by npm with other compatible versions, or am I misunderstanding the issue?

**Comment by mantoni** [comment]
Okay, makes sense. How about just making the `dependency` version a range then? Would that work for your case as well?

**Comment by sharmilajesupaul** [comment]
Yeah that should work too, however I'm not sure what impact it will have on local development.

**Comment by mantoni** [comment]
It shouldn't have any impact on local development. `npm` will simply install the newest version compatible with the given range. Currently, I don't know which version of `eslint` is still compatible with `eslint_d`. If you can figure that out and send a PR, I'm happy to merge.

**Comment by mantoni** [comment]
`v7.3.0` Now depends on a version range allowing eslint v4 and v5. Both versions can be used in different project with the same `eslint_d` install.

I consider this resolved. If it doesn’t work as expected, please let me know.
